### ISSUE TITLE
Server includes are not copied over from the src to the build folder

### ISSUE THREAD

**Issue by keithchong** [OpenLiberty/ci.gradle#200]
My server config includes another file, like so:

```
<include location="serverInclude.xml" />
```

When the Gradle project is cleaned and re-built, the included file is not 'copied' over to build, so the server config is in error.

**Comment by keithchong** [comment]
This might be as-designed since adding the configDirectory attribute works.  libertyExtensions.md
 doesn't mention having a default value (perhaps it should be the same folder as specified by the default value for configFile)

**Comment by keithchong** [comment]
To clarify, the docs didn't mention having a default value so the issue is that there should be.   The  default value (if the configDirectory attribute was not added) should be the same 'path' as the default value path for the configFile attribute.

That way, it makes the server.xml notation more inituitive.
<include location="serverInclude.xml" />

**Comment by jjvilleg** [comment]
The configDirectory currently doesn't have a default value. It is only used if it is set. Do you think it makes more sense for the default value to be set to the default path of the configFile, or what ever the configFile is set to?

**Comment by keithchong** [comment]
Yes, basically, the default should be the path where ever the source config file is.

**Comment by aguibert** [comment]
This has also been requested in the Maven plugin here https://github.com/WASdev/ci.maven/issues/427

Hopefully this can be implemented as it gives a nice usability improvement to the plugin.

**Comment by ashtonbatty** [comment]
Files and directories I place in `src/main/liberty/config` are getting copied for me, though I do note that the deploy task doesn't seem to actually process the includes, such that if I have an `<enterpriseApplication .../>` in an included config instead of the base server.xml, deploy reports:

> At least one application is not defined in the server configuration but the build file indicates it should be installed in the apps folder. Application configuration is being added to the target server configuration dropins folder by the plug-in.

**Comment by cherylking** [comment]
@ashtonbatty Can you open a separate issue for what you are seeing with recreate steps? The includes **are** processed when looking for application locations. So we need to know your exact scenario to see what might be going wrong.

**Comment by ashtonbatty** [comment]
No problem, I'll try recreate the issue with a minimal version of our project then raise a new issue.

**Comment by cherylking** [comment]
Closing this issue as the 3.x release made several improvements in this area. The configDirectory now defaults to src/main/liberty/config and can be overridden. All contents of that directory are copied over to the target server.
