### ISSUE TITLE
installLiberty task reports UP-TO-DATE when liberty version changes

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/ci.gradle#221]
Recently I updated a project to use the latest beta:

```js
    liberty {
        install {
            // use 1 liberty install for the whole repo
            baseDir = rootProject.buildDir
            runtimeUrl = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/beta/wlp-beta-2018.2.0.0.zip"
        }
    }
```

And got a failure when features present in the new beta could not be found by the runtime or installed by installUtility.  Turns out this is because the `installLiberty` task is considered to be up-to-date if `liberty.install.baseDir` exists, but it does not check to make sure it's the right version of liberty installed.

The `libertyInstall` task should be updated to compare product versions of the maven/runtimeUrl dependency to the product version in `${liberty.install.baseDir}/lib/versions/WebSphereApplicationServer.properties` to ensure the runtime itself is up to date.

**Comment by cherylking** [comment]
I don't think this is as straight forward as stated above. In addition to checking the version in WebSphereApplicationServer.properties (e.g. com.ibm.websphere.productVersion=17.0.0.4), you would also need to check the product edition (com.ibm.websphere.productEdition=LIBERTY_CORE) right?

In the following scenario,  if the runtimeUrl were changed from https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/17.0.0.4/wlp-webProfile7-17.0.0.4.zip to https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/17.0.0.4/wlp-javaee7-17.0.0.4.zip, the version for both is 17.0.0.4 but there is still a difference. I presume that in that case, the libertyInstall task would need to detect the difference and update the installation. Do you agree @aguibert ?

If so, can all the various zip archives be mapped to specific productEdition values? Or do multiple map to the same productEdition value? I'm not sure we can definitively tell which runtimeUrl was used for the current installation (shy of caching it somewhere).

**Comment by aguibert** [comment]
It's worth noting that the plugin will always download the jar (if it does not exist in maven cache), so we don't need to figure out whether or not it's up-to-date just by looking at the URL.

So, given that we always have the zip archive to look at, we can inspect the `WebSphereApplicationServer.properties` file without extracting the zip and check its contents against what is already extracted in `liberty.install.baseDir`.

**Comment by jjvilleg** [comment]
@aguibert  the installLiberty ant task that gets called only runs if there is no wlp directory installed. In order to update the liberty version, we would need to remove the current wlp directory and install a fresh updated one. The problem with this is that the removed wlp could have been configured, and we would not be able to reliably translate these changes to the updated directory, since some of these changes could have been configured out of the plugin's scope. 

In this situation, if a clean is not ran, it makes more sense to throw an error stating that the wlp version has changed and that a complete rebuild would be necessary.

**Comment by cthigh** [comment]
@aguibert that's right. `createServer` will reapply the configuration files or info in the pom.

**Comment by efussi** [comment]
FWIW, here is what we are using as workaround in our project:
1. define a Gradle property `libertyVersion`
2. Amend the `installLiberty` task like this:
```gradle
            installLiberty {
                // workaround for https://github.com/WASdev/ci.gradle/issues/221:
                // if libertyVersion changes, delete the libertyHome directory first to ensure the new Liberty gets installed
                inputs.property("libertyVersion", libertyVersion)
                doFirst {
                    delete libertyHome
                }
            }
```
Now when we change the `libertyVersion` property, Gradle will consider `installLiberty` outdated and executes its task actions, the first of which deletes the existing Liberty installation to ensure we start from a clean slate. This approach may not be viable for all scenarios, but it does the trick for us.

**Comment by cherylking** [comment]
Update: Just had an inquiry on this issue from @mezarin. Let's see if we can fix this with just taking into account the version number changing.
