### ISSUE TITLE
deprecated reports.html.destination in the example build file

### ISSUE THREAD

**Issue by nnworkspace** [OpenLiberty/ci.gradle#287]
Environment:

this plugin: v2.6
Gradle: v4.10.2
Liberty: v18.0.0.3

These lines in the example caused gradle warnings:

```
test {
    reports.html.destination = file("$buildDir/reports/unit")
    reports.junitXml.destination = file("$buildDir/test-results/unit")
    exclude '**/it/**'
}
```

Problem: `destination` is deprecated. 

Could you please update your tutorial and readme file to use a more recent version of gradle, thank you!

**Comment by cherylking** [comment]
I think the replacement for `destination` is `outputLocation`. I recently modified a test to use Kotlin and had to change to that for it to work. See this [file](https://github.com/OpenLiberty/ci.gradle/blob/main/src/test/resources/server-config/testCreateLibertyConfigDir.gradle.kts#L44).
