### ISSUE TITLE
Gradle plugin: Enhancements and parity with Maven plugin 3.x

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/ci.gradle#330]
Enhance the Gradle plugin to be at par with 3.x of the Maven plugin.

**Comment by yeekangc** [comment]
Do we have a list of the updated goals in 3.x somewhere?

**Comment by cherylking** [comment]
@yeekangc Are you referring to what goals were updated in ci.maven? We have not updated any goals in ci.gradle and do not plan to (other than removing installApps once the deploy logic has been merged with those changes).

**Comment by cherylking** [comment]
This has been completed with release 3.0 of io.openliberty.tools:liberty-gradle-plugin.

**Comment by yeekangc** [comment]
This is part of the Dev Mode feature, OpenLiberty/open-liberty#8970.  The feature spawned several epics to cover the work from core Dev Mode to enhancements in the Maven and Gradle plugins to enable Dev Mode.  The work involved the move of the plugins to io.openliberty.tools too.  This epic here was for the Gradle plugin's enablement work.
