### ISSUE TITLE
Dynamic port setup

### ISSUE THREAD

**Issue by oliver-steinbrecher** [OpenLiberty/ci.gradle#362]
Hi liberty team,
we're running a jenkins which takes care of multiple projects. In order to limit side-effects we'd like to run the server with dynamic ports. How can this be achieved? :)

**Comment by mattbsox** [comment]
You could try setting up your project to set the server ports in the sever.xml through bootstrap properties. Then those bootstrap properties could be configured through Gradle project properties passed in through the command line or gradle.properties in your Jenkins instance.

**Comment by cherylking** [comment]
@oliver-steinbrecher Did you resolve your issue with setting up ports?

**Comment by oliver-steinbrecher** [comment]
Thanks for asking. We haven't really solved this but can live with the actual status.
