### ISSUE TITLE
Java process still using Liberty files after installing features on Windows part 2

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/ci.gradle#406]
The fix for #397 which appeared in OpenLiberty/ci.common#122 must be pulled into this project by updating build.gradle.

**Comment by cherylking** [comment]
The wrong issue was referenced above. It should have been https://github.com/OpenLiberty/ci.common/pull/122

**Comment by turkeylurkey** [comment]
Thank you, I didn't think of typing it that way.

**Comment by turkeylurkey** [comment]
Fixed.
