### ISSUE TITLE
Please publish to plugins.gradle.org

### ISSUE THREAD

**Issue by ashtonbatty** [OpenLiberty/ci.gradle#415]
This will make the plugin available via the `plugins` block, instead of requiring a `buildscript` block and lone `apply plugin` in every build.gradle just for the Liberty plugin.

See also #316

**Comment by cherylking** [comment]
@ashtonbatty Release 2.7 has been made available there, and we are working on getting the newly released 3.0 available there. I will update once that is done.

**Comment by cherylking** [comment]
The 3.0 release is available on plugins.gradle.org now. Note the new id.

https://plugins.gradle.org/plugin/io.openliberty.tools.gradle.Liberty
