### ISSUE TITLE
libertyCreate ignores bootstrap properties

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#424]
libertyCreate ignores bootstrap properties defined in either the bootstrap.properties file or inline configuration.

Using liberty-gradle-plugin 3.0

Steps to reproduce:
1. Using https://github.com/OpenLiberty/demo-devmode , set `default.http.port = 9081` in the file `src/main/liberty/config/bootstrap.properties` 
2. Run `gradle libertyCreate -i`
3. The server is created with overwritten bootstrap properties using the defaults (port 9080), even though there are no inline bootstrap properties in build.gradle.

Alternatively:
1. Define inline bootstrap properties for the port in build.gradle e.g. add `liberty.server.bootstrapProperties."default.http.port" = '9083'` to the `ext{}` section
2. Run `gradle libertyCreate -i`
3. The server is created with overwritten bootstrap properties using the defaults (port 9080), even though inline properties specified a different port.

In both cases above, `gradle libertyCreate -i` output shows:
```
> Task :libertyCreate
Caching disabled for task ':libertyCreate' because:
  Build cache is disabled
Task ':libertyCreate' is not up-to-date because:
  Task.upToDateWhen is false.
[ant:server] CWWKM2001I: Invoke command is [/Users/eric/git/demo-devmode/build/wlp/bin/server, create, defaultServer].
The /Users/eric/git/demo-devmode/src/main/liberty/config/bootstrap.properties file is overwritten by inlined configuration.
Generate server configuration file /Users/eric/git/demo-devmode/build/wlp/usr/servers/defaultServer/configDropins/overrides/liberty-plugin-variable-config.xml
Update server configuration file server.xml from /Users/eric/git/demo-devmode/src/main/liberty/config/server.xml
Update server configuration file bootstrap.properties from inlined configuration
Adding Liberty plugin config info to /Users/eric/git/demo-devmode/build/liberty-plugin-config.xml.
:libertyCreate (Thread[Execution worker for ':',5,main]) completed. Took 1.225 secs.
:installFeature (Thread[Execution worker for ':' Thread 7,5,main]) started.
```
and `build/wlp/usr/servers/defaultServer/bootstrap.properties` contains
```
# Generated by liberty-gradle-plugin
default.http.port=9080
default.https.port=9443
```

**Comment by cherylking** [comment]
@ericglau I followed your recreate steps and it worked just fine. The bootstrap.properties file was copied over into the server as expected.

![Screen Shot 2020-01-29 at 3 34 24 PM](https://user-images.githubusercontent.com/29436451/73399480-f0cd0e80-42ac-11ea-9443-ef681420369f.png)

**Comment by ericglau** [comment]
The problem was I had a `~/.gradle/gradle.properties` file with `liberty.server.bootstrapProperties."default.http.port" = 9080` which was overriding the values.  Cancelling this issue.
