### ISSUE TITLE
LibertyDev error Cannot get property 'baseName' on null object with spring boot app

### ISSUE THREAD

**Issue by hearit-danny** [OpenLiberty/ci.gradle#452]
Using pugins:
* `io.openliberty.tools:liberty-gradle-plugin:3.0` - in buildscript block
* `"org.springframework.boot" version "1.5.10.RELEASE"`
* `groovy`
* `war`

I have a spring boot app (with no embedded server) that we assemble into a war and run on liberty with the tag `<webApplication location="spring-boot.war"/>` using the `libertyStart` task successfully. 

I want to run this same spring-boot.war with the `libertyDev` task. What configuration do I need to make this happen? Configuration currently:
* server.xml: `<webApplication location="spring-boot.war.xml"/>`
* build.gradle: 
```
liberty {
    server {
        name = "LibertyProjectServer"
        looseApplication = true
        stripVersion = true

        features {
            acceptLicense = true
        }
    }
    install {
        runtimeUrl = "some custom url to com/ibm/websphere/appserver/runtime/wlp-javaee7/19.0.0.10/wlp-javaee7-19.0.0.10.zip"
    }
}
```

Currently if I let the `libertyDev` task run with no configuration it fails the build with an exception in in the deploy task:
```
Execution failed for task ':deploy'.
> Cannot get property 'baseName' on null object
```

Running with stacktrace:
```
Execution failed for task ':libertyDev'.
> Could not execute build using Gradle distribution 'gradle-6.2.2-all.zip'.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':libertyDev'.
	[This part of stack trace omitted because of irrelevance]
Caused by: java.lang.NullPointerException: Cannot get property 'baseName' on null object
	at io.openliberty.tools.gradle.tasks.DeployTask.installProjectArchive(DeployTask.groovy:119)
	at io.openliberty.tools.gradle.tasks.DeployTask.installLooseApplication(DeployTask.groovy:255)
	at io.openliberty.tools.gradle.tasks.DeployTask.installProject(DeployTask.groovy:147)
	at io.openliberty.tools.gradle.tasks.DeployTask$_installMultipleApps_closure5.doCall(DeployTask.groovy:111)
	at io.openliberty.tools.gradle.tasks.DeployTask.installMultipleApps(DeployTask.groovy:110)
	at io.openliberty.tools.gradle.tasks.DeployTask.deploy(DeployTask.groovy:75)
	[Next part of stack trace omitted because of irrelevance]
```

Looking at the source code of the plugin, it seems it fails to set springBootTask properly in this findSpringBootTask method resulting in this line of code `archiveBaseName = springBootTask.baseName` having a null pointer exception. 

Any help is greatly appreciated!

**Comment by ericglau** [comment]
@hearit-danny `libertyDev` and the loose application configuration currently do not support Spring Boot applications.

However, this particular error occurs when the Spring Boot plugin is specified using plugins DSL.  Could you try specifying the plugin in the `buildscript` section instead?  For example:
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0'
        classpath "org.springframework.boot:spring-boot-gradle-plugin:1.5.10.RELEASE"
    }
}
apply plugin: "org.springframework.boot"
apply plugin: 'liberty'
```

**Comment by hearit-danny** [comment]
Thanks for the reply and a solution to the error. If a spring boot application is not supported for loose application configuration, what does the spring boot code in the deploy task indicate? What supported spring boot wise?

Thanks!

**Comment by ericglau** [comment]
To clarify, the `libertyDev` task currently does not support Spring Boot applications because `libertyDev` requires loose application configuration.  For Spring Boot applications, the looseApplication flag will be ignored and will be set to `false`.  This can be seen in the output if using `-i` with the `gradle` command:
`Loose application configuration is not supported for packaging type springboot. The project artifact will be installed as an archive file.` 

You can use the `deploy` and `libertyStart` tasks with Spring Boot application war files.
