### ISSUE TITLE
"taskdef class io.openliberty.tools.ant.install.InstallLibertyTask cannot be found"

### ISSUE THREAD

**Issue by nicklasb** [OpenLiberty/ci.gradle#455]
Hi! 
I am running version 3.0. and is trying to use the plugin under gradle, and until now, it have worked, however now, I have started getting this error when I run dependent tasks, like libertyCreate or libertyStart:
```
Execution failed for task ':installLiberty'.
> taskdef class io.openliberty.tools.ant.install.InstallLibertyTask cannot be found
```
The relevant parts of settings.gradle.kts (using Kotlin) looks like this:

```
buildscript  {
    repositories {

        maven {
            url = uri("https://localcache-doesnt-matter-if-i-use-sonatype")
        }
    }
    dependencies {
        classpath ("io.openliberty.tools:liberty-gradle-plugin:3.0")
    }
}
```
and the build.gradle.kts like:
```
plugins {
    java
    war
    `kotlin-dsl`
    id("liberty")
}
```

liberty-ant-tasks-1.9.3.jar is present in the .gradle cache so that seems to be available. 
However it seems that liberty-gradle-plugin doesn't find or load it for some reason.

**Comment by mattbsox** [comment]
This seems like it could be a caching problem to me. I would try cleaning your root and project Gradle caches and stopping any running Gradle daemons.

**Comment by nicklasb** [comment]
I just started looking att AntClassLoader and Kotlin, to see if that would be something, could't find anything. I have no idea why I am just having problems with the Liberty plugin. 
Is it uncommon to use AntClassLoader?

**Comment by mattbsox** [comment]
Can you try removing the plugin from `plugins` and apply it like this?

```
apply plugin: 'liberty'
```

I'm wondering if it's an issue related to the `plugins` block since we have some known issues there.

**Comment by nicklasb** [comment]
Ok, I tried using various forms of 
apply(plugin = "liberty").
Interestingly, that just made things not resolve, which was kind of weird:
```
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:42:1: Unresolved reference: liberty
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:44:5: Unresolved reference: server
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:57:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:58:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:59:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:60:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:61:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:62:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:63:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:64:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:65:5: Unresolved reference: libertyFeature
e: C:\CCShare\projects\IPPF_gradle\build.gradle.kts:66:5: Unresolved reference: libertyFeature
```

**Comment by nicklasb** [comment]
Well. This is getting even stranger.

I tried another variant, using plugin management in settings.gradle.kts:
```
pluginManagement   {
    repositories {
        gradlePluginPortal()
        maven {
            url = uri("http://artifactory.shbmain.shb.biz/maven-repo.maven.apache.org")
            setAllowInsecureProtocol(true)
        }
    }
}
```
and 
```

plugins {
    java
    war
    `kotlin-dsl`
    id("io.openliberty.tools.gradle.Liberty") version "3.0"
}
```
That resolved ok, but then produced a completely different error (while still calling installLiberty):

´´´
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\CCShare\projects\IPPF_gradle\build.gradle.kts' line: 9

* What went wrong:
An exception occurred applying plugin request [id: 'io.openliberty.tools.gradle.Liberty', version: '3.0']
> Failed to apply plugin [id 'io.openliberty.tools.gradle.Liberty']
   > Could not create task ':compileJSP'.
      > Could not create task of type 'CompileJSPTask'.
         > Could not generate a decorated class for type CompileJSPTask.
            > io/openliberty/tools/ant/ServerTask
´´´

**Comment by nicklasb** [comment]
That seems to be this one: https://github.com/OpenLiberty/ci.gradle/issues/441

Phew.

**Comment by nicklasb** [comment]
Ok. I reverted back to 2.7, and then it started working again. 
And that was just using the plain id("net.wasdev.wlp.gradle.plugins.Liberty") version "2.7".

The reason I tried with 3.0 was that I had a problem with "Bundle <properties/someenvironmentfile> for utf8 could not be found", but that is another issue if I can't find out why that happens.

**Comment by nicklasb** [comment]
Hi again, 

I have basically restructured the whole project, and after I got it to work, I tried 3.0 again, thinking what with so many changes. 

Howerver, I got stuck again. But I am thinking that there is some dependency not being there:
```
"taskdef class io.openliberty.tools.ant.install.InstallLibertyTask cannot be found
   using the classloader AntClassLoader [C:\Users\username\.gradle\caches\modules-2\files-2.1\..."

```
I have tried to add io.openliberty.tools:liberty-ant-tasks:1.9.3 _everywhere_, as a dependency using classpath, the file using a flatdir and to the classpath manually. Sadly I do not seem to have sufficient wizardry to succeed with getting io.openliberty.tools.ant.install.InstallLibertyTask into the AntClassLoader. 

Is there something everybody else has that I don't? Has is something to do with Kotlin vs Groovy, differences in the dsl:s perhaps?

**Comment by nicklasb** [comment]
I am not sure if I am completely off the rails here, but it seems like the AntClassLoader is looking for a taskDef descendant, and io.openliberty.tools.ant.install.InstallLibertyTask doesn't seem to be that? Instead it seems to descend from ant.Task?  

(Taskdef also does: https://ant.apache.org/manual/api/org/apache/tools/ant/taskdefs/Taskdef.html)

**Comment by nicklasb** [comment]
@mattbsox Looking into the source and what the AntClassLoader actually gets into its class path, it seems that it is not a matter of descendence, but simply that it cannot find io.openliberty.tools:liberty-ant-tasks:1.9.3. It is in the cache and I see that it is a dependency in the maven repo, but something else is wrong. 

It doesn't seem to be in whatever configuration the plugin uses, I haven't been able to pinpoint it to manually add liberty-ant-tasks to it, also "runtime" as the pom says . Do you know? 

Or is it something else?

**Comment by mattbsox** [comment]
@nicklasb It seems this boils down to a difference in the way Gradle will inspect the classes of a plugin depending on how the plugin is applied.

When using the `plugins` block to apply a plugin, i.e:

```
plugins {
    id('liberty')
}
```

Gradle will look at all the methods and fields of the plugin classes. Since some of our classes aren't on the classpath at that time, Gradle won't be able to find them resulting in the `taskdef` class not found error.

This isn't the case when you apply the plugin with the old method of `apply plugin: 'liberty'` which is outside of the plugins block at the root level of the build.gradle file:

```
buildscript {
    repositories{
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0'
    }
}

apply plugin: 'liberty'
```

Here Gradle just checks the constructors of the plugin classes, so the fact that the classes aren't present at that time doesn't affect anything.

The plugin will work the same when applied through either method, but the plugin can't pass the inspection when applied through the `plugins` block.

It looks like we'll need to restructure some of the plugin files/dependencies to get around this issue.

As for any issues pertaining to the Gradle Kotlin DSL, we'll need to check our current level of support. Currently, we don't have any test projects that use a Kotlin build file so there may very well be some issues that are not on our radar.

**Comment by nicklasb** [comment]
@mattbsox 
Thanks for your reply!
So you mean that a resolution to #441 would perhaps fix this issue?

A fix would be greatly appreciated, I think we could see measurable gains in our process by being able to use 3.0. (Also, the CPU cycles of them big irons of yours don't come for free. :-) )

WRT Kotlin, it would be problematic if that were to be the problem.
Seems odd though, so many other plugins would fail if there was some general problem with Kotlin.

**Comment by cherylking** [comment]
@nicklasb We think we have fixed this problem with our latest milestone release (3.1-M3) if you would like to give it a try.

**Comment by nicklasb** [comment]
> @nicklasb We think we have fixed this problem with our latest milestone release (3.1-M3) if you would like to give it a try.

Regrettfully, we had to go with Maven and I am also not involved in that project anymore, I have no real opportunities to check if that works, I am afraid. I will report if I that happens.

**Comment by cherylking** [comment]
@nicklasb No worries...thank you for all the debugging you did into the problem. I will close the issue and it can be reopened if needed.
