### ISSUE TITLE
gradle libertyDev

### ISSUE THREAD

**Issue by hanymorcos** [OpenLiberty/ci.gradle#478]
I'm using Git Bash. I'm running into an error with libertyDiv task.  I also having the same issue in in Intellij. 

https://stackoverflow.com/questions/62580927/gradle-liberty-no-such-property-outputdir-for-class-org-gradle-api-internal-fi

Error to execute task libertyDev using gradle-3.2.1.

Execution failed for task ':libertyDev'.

No such property: outputDir for class: org.gradle.api.internal.file.DefaultSourceDirectorySet

IF I switch to gradle-6.4.1 I get a different error. hanym@LAPTOP-EQC0BINN MINGW64 ~/liberty/demo-devmode (master) $ gradle libertyDev Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

Task :libertyDev FAILED

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':libertyDev'.
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.4.1-bin.zip'.

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 16s 1 actionable task: 1 executed

hanym@LAPTOP-EQC0BINN MINGW64 ~/liberty/demo-devmode (master)

hanym@LAPTOP-EQC0BINN MINGW64 ~/liberty/demo-devmode (master) $ gradle --version

Gradle 6.4.1
Build time: 2020-05-15 19:43:40 UTC Revision: 1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin: 1.3.71 Groovy: 2.5.10 Ant: Apache Ant(TM) version 1.10.7 compiled on September 1 2019 JVM: 1.8.0_252 (Eclipse OpenJ9 openj9-0.20.0) OS: Windows 10 10.0 amd64

**Comment by cherylking** [comment]
The first error I believe is due to the very old version of Gradle (3.2.1). When you switched to Gradle 6.4.1, the error you got seemed to be due to an already running Gradle daemon. Can you try stopping the Gradle daemon and cleaning up the Gradle cache before running again?

**Comment by mattbsox** [comment]
Also add `--info --stacktrace` to the end of the command for more info on the exception.

**Comment by hanymorcos** [comment]
Just clearing the cache and stopping the daemon made it work. Thanks.
