### ISSUE TITLE
Document the SpringBootExtension

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/ci.gradle#479]
Support was added for SpringBoot Uber jar applications in 2.6 release. Here is the extension for it: https://github.com/OpenLiberty/ci.gradle/blob/master/src/main/groovy/io/openliberty/tools/gradle/extensions/SpringBootExtension.groovy

Need to create a document describing that extension and add a link to it either at the bottom of the readme, in the `deploy.md`, or in the `libertyExtensions.md`.

**Comment by mattbsox** [comment]
Docs for our Maven plugin SpringBoot support: https://github.com/OpenLiberty/ci.maven/blob/master/docs/spring-boot-support.md

**Comment by cherylking** [comment]
It has been added here: https://github.com/OpenLiberty/ci.gradle/blob/master/docs/spring-boot-support.md#spring-boot-support
