### ISSUE TITLE
A configured application must be installed to the apps folder.

### ISSUE THREAD

**Issue by hanymorcos** [OpenLiberty/ci.gradle#483]
Can I get some feedback on what is the issue  here? 

> The application, test, is configured in the server.xml and the plug-in is configured to install the application in the dropins folder. 
A configured application must be installed to the apps folder.

liberty {

    server {
        baseDir = 'C:\\liberty_home\\'
        name = 'test'
        timeout= 1600
        deploy {
            apps = [file('build/libs/test.war')]
            dropins = [war]
        }
    }
}

**Comment by mattbsox** [comment]
You're installing an app that is configured in your `server.xml` to both `apps` and `dropins`. The plugin doesn't allow an app to be configured in the `server.xml` and be installed to `dropins`. You'll need to remove the `dropins` line or remove the application configuration from your `server.xml`.

**Comment by mattbsox** [comment]
If you remove the app configuration from your `server.xml` I would also remove the `apps` line since it is unnecessary and could conflict with the app installed to `dropins`.

**Comment by hanymorcos** [comment]
I can use just the dropins. What line of the server.xml should I remove <WebApplication>? I need server.xml to configure feature and JNDI.

**Comment by hanymorcos** [comment]
I also need to configure a timer to watch dropins folder.

**Comment by hanymorcos** [comment]
WebApplication tag?

**Comment by cherylking** [comment]
Can you include your server.xml here or the relevant snippets?

**Comment by hanymorcos** [comment]
<server description="test">

    
    <featureManager>
        <feature>jsp-2.3</feature>
        <feature>localConnector-1.0</feature>
    </featureManager>


       <include location="${shared.config.dir}/jndi-include.xml"/>
       <variable name="jdbcuser" value="jdbc"/>


    
    <httpEndpoint httpPort="10085" httpsPort="10445" id="defaultHttpEndpoint"/>

    
    <applicationManager autoExpand="true"/>

    <applicationMonitor updateTrigger="mbean"/>

    <webApplication contextRoot="services/test" id="lavender.test" location="test.war" name="test"/>
</server>

**Comment by hanymorcos** [comment]
<server description="test">

    
    <featureManager>
        <feature>jsp-2.3</feature>
        <feature>localConnector-1.0</feature>
    </featureManager>


       <include location="${shared.config.dir}/jndi-include.xml"/>
       <variable name="jdbcuser" value="jdbc"/>


    
    <httpEndpoint httpPort="10095" httpsPort="10445" id="defaultHttpEndpoint"/>

       <applicationManager autoExpand="true"/>

    <applicationMonitor updateTrigger="lbean"/>

    <webApplication contextRoot="services/test" id="test" location="test.war" name="test"/>
</server>

**Comment by hanymorcos** [comment]
I'm good.
