### ISSUE TITLE
Adding liberty plugin to init.gradle failing. 

### ISSUE THREAD

**Issue by hanymorcos** [OpenLiberty/ci.gradle#493]
Anyone got the liberty plugin working from init.gradle?

Thanks,

H

$ cat ~/.gradle/init.gradle
allprojects{

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0'
    }
}
  apply plugin: 'liberty'
}

$ gradle libertydev
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\hanym\.gradle\init.gradle' line: 11

* What went wrong:
Plugin with id 'liberty' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by cherylking** [comment]
I found if I applied the plugin as follows (with the implementation class) it worked. Can you verify this fixes your issue?

```
initscript {
   repositories {
      mavenCentral()
   }
   dependencies {
      classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0'
   }
}
allprojects {
  apply plugin: io.openliberty.tools.gradle.Liberty
}
```

**Comment by cherylking** [comment]
Looks like this may be a known issue with Gradle.

https://github.com/gradle/gradle/pull/9594
https://github.com/gradle/gradle/issues/1322

**Comment by hanymorcos** [comment]
works. Thanks.
