### ISSUE TITLE
Devc mode: hot change in gradle extension not reflected on server

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/ci.gradle#508]
1. Use project https://github.com/OpenLiberty/demo-devmode
2. Run `gradle libertyDevc`
3. Modify `build.gradle` and change `liberty.server.var.artifactId = "${rootProject.name}"` to `liberty.server.var.artifactId = "foo"` The container restarts.
4. In a browser hit `http://localhost:9080/` and the usual app demo-devmode-gradle will run instead of the Open Liberty splash screen. Expected app "foo" not to be found.

**Comment by cherylking** [comment]
Are they `liberty.server.var` properties being monitored for changes?

**Comment by cherylking** [comment]
That property would be in the generated liberty-plugin-config-variable.xml. Is that file copied to the container?
