### ISSUE TITLE
ant.ServerTask error 

### ISSUE THREAD

**Issue by hanymorcos** [OpenLiberty/ci.gradle#510]
I'm getting the following error. I couldn't a good feedback on the error. 

Thanks,

Hany

* What went wrong:
Execution failed for task ':libertyCreate'.
> taskdef class io.openliberty.tools.ant.ServerTask cannot be found
   using the classloader AntClassLoader[]

**Comment by cherylking** [comment]
This is probably the same issue described in the following and we are still trying to work around it. Gradle changed how it inspects classes when the plugin is applied and that is causing this problem. See this comment in particular https://github.com/OpenLiberty/ci.gradle/issues/455#issuecomment-640869214. If you can change how you apply the plugin, it may get around the problem.

https://github.com/OpenLiberty/ci.gradle/issues/441
https://github.com/OpenLiberty/ci.gradle/issues/455

**Comment by hanymorcos** [comment]
https://github.com/OpenLiberty/ci.gradle/issues/493

Using build script in the build.gradle file works.  But using the init.gradle method it breaks. 

Thanks,

Hany
