### ISSUE TITLE
Version of ant 1.8.4 that the liberty-gradle-plugin depends on has a security vulnerability

### ISSUE THREAD

**Issue by scottdickerson** [OpenLiberty/ci.gradle#521]
The classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.7' is bringing in ant version 1.8.4 which has a security issue according to this: https://seclists.org/oss-sec/2020/q2/106

Description: Apache Ant 1.1 to 1.9.14 and 1.10.0 to 1.10.7 uses the default temporary directory identified by the Java system property java.io.tmpdir for several tasks and may thus leak sensitive information. The fixcrlf and replaceregexp tasks also copy files from the temporary directory back into the build tree allowing an attacker to inject modified source files into the build process.
Resolution: Upgrade to version org.apache.ant:ant-junitlauncher:1.10.8;org.apache.ant🐜1.9.15,1.10.8

**Comment by cherylking** [comment]
@scottdickerson fyi...version 2.7 of the liberty-gradle-plugin is quite old. We have released a newer version here: https://plugins.gradle.org/plugin/io.openliberty.tools.gradle.Liberty/3.0

However, it looks like the newer version still uses org.apache.ant 1.8.4. So we will look into updating this. Thanks for bringing to our attention.
