### ISSUE TITLE
"gradle clean" fails on Windows after running devc

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/ci.gradle#542]
`gradle clean` fails to delete some files in the `build` directory after running `devc`.
Trying to manually delete the `build` directory is blocked due to permission issues.
The current workaround is to logout of the Windows account and log back in, and then manually delete the `build` directory.

```
Execution failed for task ':clean'.
> Unable to delete directory 'C:\Users\TREVORCrawford\Git\oct-demo-devmode\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\TREVORCrawford\Git\oct-demo-devmode\build\wlp\usr\servers\defaultServer\dropins
    - C:\Users\TREVORCrawford\Git\oct-demo-devmode\build\wlp\usr\servers\defaultServer
    - C:\Users\TREVORCrawford\Git\oct-demo-devmode\build\wlp\usr\servers
    - C:\Users\TREVORCrawford\Git\oct-demo-devmode\build\wlp\usr
    - C:\Users\TREVORCrawford\Git\oct-demo-devmode\build\wlp
```

**Comment by turkeylurkey** [comment]
Could you add more detail such as what file was in the dropins directory? Any special procedures?

**Comment by TrevCraw** [comment]
@turkeylurkey I'm not actually sure there were any files in the `dropins` dir. It seems to have a problem with everything in the `build` dir. 

There was nothing special done. Just run `devc` normally, exit dev mode, and then run `gradle clean`. @ericglau was able to reproduce in his Windows env as well.

**Comment by turkeylurkey** [comment]
I worked on reproducing this for two hours but I could not.

**Comment by ericglau** [comment]
I'll see if I can reproduce this again and look into it from there.

**Comment by ericglau** [comment]
I cannot reproduce this issue now either.

Tried liberty-gradle-plugin:3.1-M3 - ran libertyDevc then clean.  Clean fails with the below (since it did not skip installing features), but can be worked around according to https://github.com/OpenLiberty/ci.gradle/blob/master/docs/clean.md with `gradle --stop` then clean again.
```
> java.io.IOException: Unable to delete directory 'C:\Users\Eric\git\demo-devmode\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\Eric\git\demo-devmode\build\wlp\lib\com.ibm.ws.install_1.0.46.jar
    - C:\Users\Eric\git\demo-devmode\build\wlp\lib
    - C:\Users\Eric\git\demo-devmode\build\wlp
```

Tried liberty-gradle-plugin:3.1-M4-SNAPSHOT from master - ran libertyDevc then clean.  Clean succeeded.

**Comment by ericglau** [comment]
@TrevCraw Please see if this issue still occurs for you, otherwise you can close it.  Thanks.

**Comment by TrevCraw** [comment]
Cannot reproduce anymore. Closing.
