### ISSUE TITLE
Support dev mode parameters through a Gradle extension

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#544]
[Dev mode parameters](https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#command-line-parameters) are currently only supported through command line when used with `gradle libertyDev`.  To allow these parameters to be provided through a build.gradle for consistency, we should also allow these to be supported through a Gradle extension.

For reference, the [`libertyDevc` task already supports the `dev` extension](https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#properties-1) for container specific parameters.

**Comment by cherylking** [comment]
@ericglau Did you already add this here?
https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#properties-1

**Comment by ericglau** [comment]
The dev extension for libertyDevc makes sense since those parameters are related to the project, so they should be allowed to be specified in the build.gradle file.  For regular dev mode parameters, those are related to what you are currently running (i.e. your current invocation of dev mode), not related to the project itself.  So they should only be specified in the command line.  

Cancelling this for the reasons above.  This can be reopened if there is a need for it.
