### ISSUE TITLE
installFeature doc says it can take a URL but it doesn't work

### ISSUE THREAD

**Issue by ind1go** [OpenLiberty/ci.gradle#548]
Over at [installFeature](https://github.com/OpenLiberty/ci.gradle/blob/master/docs/installFeature.md) it says that `name` is an array, the elements of which:

> can be a file name or a URL to the ESA file.

However, I've tried the following:

```gradle
liberty {
    server {
        features {
            name = ["https://my-host.com/path/to/my.esa"]
            acceptLicense = true
        }
    }
}
```

And this doesn't work:

```
CWWKM2002E: Failed to invoke [/path/to/my/project/build/wlp/bin/installUtility, install, --acceptLicense, https://my-host.com/path/to/my.esa]. RC= 20 but expected=[0, 22].
```

Trying to run the same direct via `installUtility` I get:

```
CWWKF1267E: The file /path/to/my/project/build/wlp/https:/my-host.com/path/to/my.esa does not exist.
```

... so it's being interpreted as a local file. I also can't find any tests around the place to confirm that the name can be a URL.

**Comment by cherylking** [comment]
Given that `installUtility` does not handle it, I think we need to use this issue to change our documentation. I looked up the documentation for installUtility and it does not mention supporting URLs.

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_installutility.html

**Comment by cherylking** [comment]
I have verified that URLs are not supported. I will update our doc accordingly.
