### ISSUE TITLE
Eclipse is unable to import gradle project that is using this plugin

### ISSUE THREAD

**Issue by dkrtic** [OpenLiberty/ci.gradle#563]
When one tries to import a project, Eclipse fails with the folowing error:
> Java Model Exception: Java Model Status [Test source folder 'src/test/java' in project 'test' must have an output folder that is not also used for main sources]

The reason is that the plugin is the setting the output folders to the same folder, for every source folder, including the tests.
This is done in https://github.com/OpenLiberty/ci.gradle/blob/3fd0946fc2ba4957cdca0287f2f01f7cf2e10903/src/main/groovy/io/openliberty/tools/gradle/Liberty.groovy#L132

When this is changed so that only main sources output folder is changed, project import is working.
I have tested it by changing the line
https://github.com/OpenLiberty/ci.gradle/blob/3fd0946fc2ba4957cdca0287f2f01f7cf2e10903/src/main/groovy/io/openliberty/tools/gradle/Liberty.groovy#L142
to:
`if (source.kind == 'src' && source.hasProperty('output') && source.output == 'bin/main') {`

**Comment by cherylking** [comment]
Thank you for reporting this. We will look into making the necessary change.
