### ISSUE TITLE
Incorrect classpath source when importing project into VS Code Java

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#565]
1. Clone https://github.com/openliberty/guide-gradle-intro
2. Open the `finish` project with VS Code
3. Install [Language Support for Java](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension in VS Code
4. Set the extension to Standard mode which is needed for debugging (VS Code: Preferences, Settings, search `java.server.launchMode` and set to Standard).
5. Then make a change in any Java file (e.g. HelloServlet.java) and save it.  This causes the build folder to be created with a ton of recursive build folders within it.

![image](https://user-images.githubusercontent.com/29640130/99560141-88623180-2993-11eb-8c84-381ef6aad89f.png)

The problem is that the `.classpath` file is being generated with:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path=""/>
	<classpathentry kind="output" path="build/classes/java/main"/>
</classpath>
```
So it is taking the entire project root as source, and building it into the output dir.  The `src` `path` is incorrect in the above.  If I change the `src` `path` to "src/main/java", then it works properly.

**Comment by ericglau** [comment]
This may be related to https://github.com/OpenLiberty/ci.gradle/issues/563 and this area of the code: https://github.com/OpenLiberty/ci.gradle/blob/e4f9ede7a5034c141dc6953a2401b297e4ae44d6/src/main/groovy/io/openliberty/tools/gradle/Liberty.groovy#L136

**Comment by cherylking** [comment]
@ericglau Did PR #566  fix this issue?
