### ISSUE TITLE
Identify and fix issues related to Gradle 7 support

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/ci.gradle#592]
A customer reported the following error when trying to run libertyDev task with Gradle 7:
Type 'DevTask' property 'container' is missing an input or output annotation.

The fix for that particular issue can be found in this PR: #590 

However, we would need to identify and fix all issues related to Gradle 7 support, not just this one. @ericglau found the following when attempting to run with Gradle 7:

```
A problem was found with the configuration of task ':installLiberty' (type 'InstallLibertyTask').
  - Type 'InstallLibertyTask' property 'libertyRuntimeConfiguration' has @Input annotation used on property of type 'Configuration'.
    Reason: A property of type 'Configuration' annotated with @Input cannot determine how to interpret the file.
    Possible solutions:
      1. Annotate with @InputFile for regular files.
      2. Annotate with @InputDirectory for directories.
      3. If you want to track the path, return File.absolutePath as a String and keep @Input.
    Please refer to https://docs.gradle.org/7.0-rc-2/userguide/validation_problems.html#incorrect_use_of_input_annotation for more details about this problem.
```
We currently support Gradle 6 and should look into these Gradle 7 issues. Currently milestone 1 is available for Gradle 7.

**Comment by corporate-gadfly** [comment]
gradle 7.0 is now GA.

**Comment by cherylking** [comment]
https://docs.gradle.org/7.0/release-notes.html

**Comment by corporate-gadfly** [comment]
Gradle [7.0.2](https://docs.gradle.org/7.0.2/release-notes.html) has been released.

**Comment by sweetsz** [comment]
Hi, I would like to ask  how you progressed with this issue to support Gradle 7.0.2, and when you plan release new version of io.openliberty.tools.gradle.Liberty. Thank you.

**Comment by cherylking** [comment]
@sweetsz We have pushed a snapshot to Sonatype with the changes if you would like to test it out - 3.1.3-SNAPSHOT. As for when the next release will happen, I will need to check with the team and determine what other issues/PRs need to go in first. I will post an update here within the next few days.

**Comment by cherylking** [comment]
@sweetsz @corporate-gadfly We plan to put out a 3.2 release with the Gradle 7 support by the end of this month.
