### ISSUE TITLE
command line property -Pliberty.runtime.version does not override default OL runtime version

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/ci.gradle#607]
When I run this command that defines the -Pliberty.runtime.version property (For example: gradle libertyDev -Pliberty.runtime.version=21.0.0.3), the Liberty version installed is the latest one and not the version specified. 
This happens whether or not I specify the libertyRuntime dependency in build.gradle.

According to this documentation: https://github.com/OpenLiberty/ci.gradle/blob/main/docs/installLiberty.md, and the example command above, OL version 21.0.0.3 should have been resolved/installed.

I can workaround this by having a gradle.properties file with the above property specified, or I can define/override the liberty version directly in build.gradle (i.e. under dependencies or liberty.runtime).

**Comment by cherylking** [comment]
@ericglau The `InstallLibertyTask` looks for the `liberty.runtime` project properties in `buildInstallLibertyMap()`. Does the `DevTask` need to do something to pass those along to the `BuildLauncher` that calls `libertyCreate`?
