### ISSUE TITLE
Equivalent to copyDependencies Maven plugin feature

### ISSUE THREAD

**Issue by lfielke** [OpenLiberty/ci.gradle#619]
I'm trying use the Gradle plugin to build and package a web app that uses JDBC drivers. I'm using Gradle to manage all the other dependencies, so I'd like to avoid copying the JDBC driver JAR somewhere manually. I can see the Open Liberty docs [1] mention the Maven plugin has a `copyDependencies` element that can be used to copy a driver JAR to a folder, which can then be referenced in `server.xml`.

I might be just missing something, but I cannot see how to do this with the Gradle plugin.

I think my desired behaviour is to be able to add some dependencies to a Gradle configuration and have them copied into the server during `installServer`. Perhaps like:

```groovy
libertyLib 'org.xerial:sqlite-jdbc:3.36.0.1'
libertyLib 'org.postgresql:postgresql:42.2.23'
```

I would then add the `<library>` element to `server.xml` (as in the linked doc page), knowing that the jars (and their transitive dependencies) would be in some well-known location.

This is the first time trying Open Liberty to run our existing web apps, so apologies if I've missed some other obvious way to solve this problem.

1: https://openliberty.io/docs/21.0.0.7/relational-database-connections-JDBC.html#_jdbc_driver_library_configuration

**Comment by mattbsox** [comment]
You can use a `Copy` task to accomplish this. You'll just need to add it to your current build lifecycle.

```
task copyJDBC {
    doLast {
        copy {
            from configurations.libertyLib
            into ""$buildDir/wlp/usr/servers/<YourServerName>/jdbc""
            include '*.jar'
        }
    }
}
```

This will copy the jars into a `jdbc` folder in the server directory (server.config.dir) like `copyDepednencies` does in our Maven plugin.

You'll want to set it up to run after the server has been created. I would probably add it as a dependency for the `deploy` task.

```
deploy.dependsOn 'copyJDBC'
```

This ensures that the server has been created and will run before the application is deployed to the server.

**Comment by lfielke** [comment]
Thanks for the tip, that works. It's much easier to create an ad-hoc task in Gradle than in Maven, so perhaps the Gradle plugin doesn't need this built in.

**Comment by dmuelle** [comment]
> You can use a `Copy` task to accomplish this. You'll just need to add it to your current build lifecycle.
> 
> ```
> task copyJDBC {
>     doLast {
>         copy {
>             from configurations.libertyLib
>             into ""$buildDir/wlp/usr/servers/<YourServerName>/jdbc""
>             include '*.jar'
>         }
>     }
> }
> ```
> 
> This will copy the jars into a `jdbc` folder in the server directory (server.config.dir) like `copyDepednencies` does in our Maven plugin.
> 
> You'll want to set it up to run after the server has been created. I would probably add it as a dependency for the `deploy` task.
> 
> ```
> deploy.dependsOn 'copyJDBC'
> ```
> 
> This ensures that the server has been created and will run before the application is deployed to the server.

**Comment by cherylking** [comment]
@dmuelle Is there a reason this issue was reopened by you back in July? It seemed as though Matt had provided the solution. We do not intend to add `copyDependencies` to Gradle given the flexibility to add things to the build life cycle.

**Comment by dmuelle** [comment]
@cherylking the only reason I reopened it was because I had accidentally closed it right before. I'm not sure how I closed it, but I was just trying to undo my mistake. Sorry for the confusion.

**Comment by cherylking** [comment]
@dmuelle Ok, I'm going to go ahead and close it now since we do not plan to add anything for this. Thanks.
