### ISSUE TITLE
Generate features, improve error message when class files do not exist 

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/ci.gradle#665]
Running `gradle generateFeatures` on a project without any class files, a StackOverflow error is returned:
```
kathrynkodama@MacBook-Pro demo-devmode-scan % gradle generateFeatures

> Task :generateFeatures
Parsing the server file /Users/kathrynkodama/devex/featureGeneration/demo-devmode-scan/src/main/liberty/config/server.xml1 for features and includes.
Parsing the server file /Users/kathrynkodama/devex/featureGeneration/server.xml for features and includes.
null

> Task :generateFeatures FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateFeatures'.
> java.lang.StackOverflowError (no error message)

```

Improve this error message to indicate that users should run `gradle compileJava` first.

**Comment by turkeylurkey** [comment]
Similarly, if there is no classes directory at all the scanner can return an exception:
`java.lang.IllegalArgumentException: CWMIG12026E: The /Users/paulg/WAS/devExperience/featureGeneration/demo-devmode/build/classes/java/main file that is specified by the binaryInputPath parameter does not exist.` We should check it exists before we call the scanner.
