### ISSUE TITLE
Proper way to debug liberty application in IntelliJ?

### ISSUE THREAD

**Issue by hearit-danny** [OpenLiberty/ci.gradle#673]
Hi, using the liberty gradle 3.x plugin, this is how I have determined to use the liberty debugger on an application in Intellij 2020+. This method seems a bit clunky compared to what you did with TWAS and I wanted to make sure there is not a better recommendation:

**Create the IntelliJ Liberty Debug Server Hook run configuration.**
1. In IntelliJ, go to the Run menu and select Edit Configurations.
2. Create a Remote configuration
3. Select the + and type remote (do not choose websphere remote).

Configuration tab should look like the following:
- Name: Liberty Debug Server Hook
- Change the port to 7777
- Set module's classpath to your top level project.

Logs tab should look like the following:
- Add the `build\wlp\usr\servers\LibertyServer\logs\messages.log` to the list of Log files to be show in the console.
- You can choose to have the log come to focus in IntelliJ after messages are printed if you wish by checking the boxes below.

**Run the debugger**
1. Run `libertyDebug` gradle task in IntelliJ
2. It will appear like the task is doing nothing and is a long running task and will run until stopped. This is normal.
3. If the server has never been started before, it may be necessary to run `libertyStart` first. `LibertyDebug` may not work off a cleaned project or cold `LibertyStart`.
4. Run the new `Liberty Debug Server Hook` run configuration in debug mode in IntelliJ
5. You will see the server now starting in the console of the Debug panel if you added in the messages.log to this run configuration in the previous steps.
6. Once the server has started, you can now use breakpoints how you normally would. 

**Done debugging**
1. Stop the debugger.
2. Stop the running `libertyDebug` task.
3. Stop the server with `libertyStop` task if you are also done with the server. The server can still run without debugging just fine.

**My observations on this process:**

1. `libertyDebug` does nothing until the debugger is connected to it, once that happens the liberty server will start in debug mode.
2. If `libertyDebug` is not running before a liberty server is started or did not start the liberty server, the debugger won't be able to connect.
3. `libertyDebug` task can be stopped/cancelled once the liberty server has been started in debug mode and the debugger will continue to work.
4. Stopping the debugger and/or the debugger task will not stop the liberty server, it needs to be stopped with the `libertyStop` task.

Thank you for your time!

**Comment by TrevCraw** [comment]
Hello @hearit-danny, thank you for posting your question. One of the recommended ways to debug Liberty applications in IntelliJ is to use Liberty dev mode. You can run dev mode with the command `gradle libertyDev`. Dev mode automatically starts the Liberty server in debug mode, so you can attach a debugger at any time. Just set up a remote debugger in IntelliJ to attach to port 7777 and run it once dev mode has started the Liberty server. More info on dev mode can be found here: https://github.com/OpenLiberty/ci.gradle/blob/main/docs/libertyDev.md. 

Another recommendation is to use the Open Liberty Tools for IntelliJ plugin, which can be found on the marketplace here: https://plugins.jetbrains.com/plugin/14856-open-liberty-tools. An example of connecting the debugger in IntelliJ can be found here: https://youtu.be/GIIhtdXwJ9A?t=235. The rest of the video shows other use cases for the Open Liberty Tools for IntelliJ plugin.

Hope this helps! Please don’t hesitate to reach out with more questions.

**Comment by hearit-danny** [comment]
Thanks for the quick response! I have had issues with liberty dev mode for anything that is not a simple WAR project, and I had actually planned to open a ticket better understanding what is supported and what issues I am seeing. More to come on that in a different issue. 

The plugin is news to me and I will explore that more. Thanks so much!
