### ISSUE TITLE
Property timeout causes a class cast exception if is set 

### ISSUE THREAD

**Issue by alvesedgar** [OpenLiberty/ci.gradle#684]
If the timeout property is available to override the 30s for waiting for the deploy to be done, i tracked down to the task DeployTask  on line https://github.com/OpenLiberty/ci.gradle/blob/0b72dc4f92df09fbb9896f35d230bb503db9621c/src/main/groovy/io/openliberty/tools/gradle/tasks/DeployTask.groovy#L646, the property is defined as String but it's used as long, should this property used on liberty start as well why exist two properties to do the same thing timeout and verifyAppStartTimeout

**Comment by mattbsox** [comment]
The two timeout variables have slightly different use cases. We'll look into simplifying/clarifying those in the future. For now I've added a fix for the casting issue that keeps the plugin behavior the same.
