### ISSUE TITLE
Custom config files are not deployed unless clean is run

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/ci.gradle#686]
If I add additional files to `src/main/liberty/config`, they are deployed when I run the `libertyStart` or `libertyCreate` tasks.

However, if I make changes to these files, they are not redeployed when I run `libertyStart` or `libertyCreate`, unless I first run `clean`.

If I add the `--info` option, I can see that gradle is skipping `libertyCreate` because "it is up-to-date".

**Comment by cherylking** [comment]
@Azquelt I understand that. I was pointing out that behavior would be expected with `dev` mode (pick up changes), but not without it.

**Comment by mattbsox** [comment]
Can you try adding `configDirectory = file("src/main/liberty/config")` to your `server` block? Think our current logic passes over the up-to-date check when it defaults the location.

**Comment by Azquelt** [comment]
@cherylking Ah, sorry, I misread.

@mattbsox Yes, adding that line does make it copy the files every time!

**Comment by Azquelt** [comment]
Poking at it some more, without adding adding the line from mattbsox, if the server directory is outside of the project (e.g. by setting `installDir`), even running `clean` doesn't cause the files to be copied.

**Comment by mattbsox** [comment]
I suspect that there's something similar causing that. Does it work correctly if you delete the `installDir` or the specific server directory?

**Comment by Azquelt** [comment]
Yes, if I delete the specific server directory it does work (the directory is recreated with the custom config files included).

**Comment by mattbsox** [comment]
Okay, probably a similar issue with a null property/default location and an up-to-date check in that case as well. I'll see what I can do about a fix for those problems.
