### ISSUE TITLE
[Question] Preferred Configuration Option for adding OpenLiberty Gradle Plugin to an OpenLiberty project

### ISSUE THREAD

**Issue by rohanKanojia** [OpenLiberty/ci.gradle#695]
## Description

Hello, I'm from [Eclipse JKube](https://github.com/eclipse/jkube) team. I'm working on adding OpenLiberty support to [Kubernetes Gradle Plugin](https://www.eclipse.org/jkube/docs/kubernetes-gradle-plugin)

This is more of a question rather than an issue. From the [README](https://github.com/OpenLiberty/ci.gradle#usage), I can see there are two ways of adding OpenLiberty Gradle Plugin to a Gradle project:
1. Adding plugin dependency to `buildscript` and then using `apply plugin`
2. Adding plugin to `plugins { }` section 

Is there any option preferred/encouraged by the OpenLiberty community (given that [1] is an old-style configuration option) ? I can see that [OpenLiberty Starter](https://openliberty.io/start/) uses [1]. 

I'm slightly confused regarding which option should we consider for detecting whether the project is OpenLiberty or not. Right now in my pull request (https://github.com/eclipse/jkube/pull/1181) I'm handling both cases (see https://github.com/eclipse/jkube/pull/1181/files#diff-df110e6cb40dffea66aef663105b0df4fd60c2d291cf3d969e71ee85fb85b563) . I discussed this with my teammates and they suggested maybe reading `buildscript` dependencies is not a good idea.

I would really appreciate if I could get some feedback regarding this from OpenLiberty community :pray:

**Comment by rohanKanojia** [comment]
@turkeylurkey  @mattbsox @cherylking: polite ping, Could you please share your thoughts on this whenever you get the time? It will really help us in moving forward with integrating OpenLiberty into Kubernetes Gradle Plugin :pray:

**Comment by cherylking** [comment]
@rohanKanojia Yesterday was a holiday in the US. Hence no reply. I don't believe one config is really preferred over the other. 

Can you expand on this part of your question?
--> I'm slightly confused regarding which option should we consider for detecting whether the project is OpenLiberty or not.

**Comment by rohanKanojia** [comment]
I'm not sure you've heard about Eclipse JKube/Fabric8 Maven Plugin. These plugins have the ability of automatically generating docker images, K8s Yaml files, helm charts etc by inspecting project plugins/dependencies. We have framework specific generators for generating opinionated docker images.

These generators are activated on certain conditions as per project configuration. For maven, we're detecting it by checking openliberty maven plugin is present: https://github.com/eclipse/jkube/blob/f3e4c1f8ba4c8eed179f11b2a776da439027ad33/jkube-kit/jkube-kit-openliberty/src/main/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGenerator.java#L41

Now we are in the process of customizing OpenLibertyGenerator to get activated in an OpenLiberty gradle project. Right now in my pull request you can I'm checking buildscript dependencies along with plugins https://github.com/eclipse/jkube/pull/1181/files#diff-df110e6cb40dffea66aef663105b0df4fd60c2d291cf3d969e71ee85fb85b563

My question is whether it is okay to check buildscript dependencies (since it's a legacy syntax) . Currently we have to look into buildscript depenencies for detecting plugin in `apply plugin: 'liberty'` syntax.

**Comment by cherylking** [comment]
As long as you are checking for both possibilities, I don't see an issue with it.

**Comment by rohanKanojia** [comment]
Thanks a lot for your reply.
