### ISSUE TITLE
Copying entire src directory in Dockerfile causing devc and feature generation error

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/ci.gradle#716]
Feature generation is on by default.

**To reproduce**
1. Generate a Gradle project using the Open Liberty starter: https://openliberty.io/start/ (SE 11, EE 8, MP 4)
Note that this is the generated Dockerfile:
```
FROM icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi

COPY --chown=1001:0 /src/main/liberty/config /config

RUN features.sh

COPY --chown=1001:0 build/libs/*.war /config/apps

RUN configure.sh
```
2. Alter the build.gradle to use the latest from main of the Liberty Gradle Plugin `3.3.1-SNAPSHOT`
3. Add the Sonatype repos to the build.gradle needed for feature generation
4. Start `gradle libertyDevc`
5. Add a class file with new API usage to the application, ie. a health check
6. Features are generated, generated-features.xml file is created. Errors after features are generated but before they are installed.
```
Copied file: /Users/kathrynkodama/Desktop/app-name-gradle/src/main/liberty/config/configDropins/overrides/generated-
features.xml to: 
/private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig15695628410367645647/configDropins/overrides/genera
ted-features.xmlParsing the server file 
/private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig15695628410367645647/configDropins/defaults/install_a
pps_configuration_1491924271.xml for features and includes.Parsing the server file 
/private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig15695628410367645647/server.xml for features and includes.Parsing the server file 
/private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig15695628410367645647/configDropins/overrides/genera
ted-features.xml for features and includes.Could not file process changes for /Users/kathrynkodama/Desktop/app-name-
gradle/src/main/liberty/config/configDropins/overrides/generated-features.xml: null
```
This may be due to this line in the Dockerfile copying the entire src directory
COPY --chown=1001:0 /src/main/liberty/config /config

**Expected behaviour**

Copying the entire source config directory is convenient for users and although it is not the recommended approach we should still not break users.
May be related to https://github.com/OpenLiberty/ci.maven/issues/1437#issue-1148417951

**Comment by TrevCraw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Untitled---183384---2017-07-20-5970eb04c4483613a5e6dc8b/issues/OpenLiberty/ci.gradle/716?planning-poker) with ZenHub @kathrynkodama @turkeylurkey

**Comment by turkeylurkey** [comment]
Couldn't reproduce. The odd thing I noticed is that liberty installed 56 features: 
```
[AUDIT   ] CWWKF0012I: The server installed the following features: [appClientSupport-1.0, appSecurity-2.0, appSecurity-3.0, batch-1.0, beanValidation-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, ejb-3.2, ejbHome-3.2, ejbLite-3.2, ejbPersistentTimer-3.2, ejbRemote-3.2, el-3.0, j2eeManagement-1.1, jacc-1.5, jakartaee-8.0, jaspic-1.1, javaMail-1.6, jaxb-2.2, jaxrs-2.1, jaxrsClient-2.1, jaxws-2.2, jca-1.7, jcaInboundSecurity-1.0, jdbc-4.2, jms-2.0, jndi-1.0, jpa-2.2, jpaContainer-2.2, jsf-2.3, json-1.0, jsonb-1.0, jsonp-1.1, jsp-2.3, jwt-1.0, managedBeans-1.0, mdb-3.2, microProfile-4.1, monitor-1.0, mpConfig-2.0, mpFaultTolerance-3.0, mpHealth-3.1, mpJwt-1.2, mpMetrics-3.0, mpOpenAPI-2.0, mpOpenTracing-2.0, mpRestClient-2.0, opentracing-2.0, servlet-4.0, ssl-1.0, wasJmsClient-2.0, wasJmsSecurity-1.0, wasJmsServer-1.0, webProfile-8.0, websocket-1.1].
```
This would interfere with this issue because you can't add a class file with new API usage to the application, ie. a health check because all the features are already installed.

After adding a new class the server (and the container) did restart as expected. However the server did print the message:
```
[ERROR   ] NO_USER_REGISTRY 
                                                                                                               defaultOrb
                                                                                                               ```
each time it started.

**Comment by turkeylurkey** [comment]
Quit dev mode and tried again and could not reproduce the `[ERROR   ] NO_USER_REGISTRY` error.

**Comment by kathrynkodama** [comment]
@turkeylurkey When the server and container restarts, do you get stuck in a continuous loop of regenerating and restarting?
