### ISSUE TITLE
Remove usage of WarPluginConvention

### ISSUE THREAD

**Issue by donat** [OpenLiberty/ci.gradle#777]
The type will be removed in Gradle 8.0.

https://github.com/OpenLiberty/ci.gradle/blob/a5f46f503aaf60b54bdb5252f440f2bbcf0d0fff/src/main/groovy/io/openliberty/tools/gradle/utils/LooseWarApplication.groovy#L5

**Comment by cherylking** [comment]
@donat Thank you for bringing this to our attention.

**Comment by cherylking** [comment]
When we add support for Gradle 8, we need to consider all the items on the [deprecated list](https://docs.gradle.org/current/javadoc/deprecated-list.html) that are scheduled for removal in Gradle 8.0.

**Comment by cherylking** [comment]
We recently added support for Gradle 8 (in release 3.6), and the `WarPluginConvention` class was still available. I just checked the deprecated list and it says this particular class is scheduled for removal in Gradle 9. So this issue should be part of the effort to support Gradle 9 whenever it comes out. There's not even an RC1 for Gradle 9 at this point. So I am going to close this issue.
