### ISSUE TITLE
Liberty server tasks blow away jvm.options

### ISSUE THREAD

**Issue by five-iron** [OpenLiberty/ci.gradle#786]
https://github.com/OpenLiberty/ci.gradle/pull/513 causes a delete of jvm.options and other configs during liberty tasks. What I guess we're supposed to do is to set up jvmOptions or jvmOptionsFile in the liberty.server block in build.gradle, or create a jvm.options in the config folder. This a problem for me because if you don't have these options set, then your server's jvm.options just gets deleted when running any liberty server gradle tasks. I'd rather just have the server's jvm.options persist instead.

Is this intended? If so, can we add an option to _not_ delete the deployed jvm.options?

**Comment by cherylking** [comment]
@five-iron If you mean the `jvm.options` in the `build` folder where the Liberty server got created gets deleted, then the answer is yes it is intended. The jvm.options should come from either the build.gradle configuration or a config file under source config folder. If you mean something else, please respond with more details.

**Comment by five-iron** [comment]
Yeah I think you've captured what I'm saying. My setup right now doesn't use a `build` folder for creating a server, I'm pointing to a preinstalled location, so the path looks like this: `C:\liberty_install_loc\wlp\usr\servers\defaultServer\jvm.options`.

How hard would it be to prevent gradle from touching this file altogether (or at least when those jvmOption-related configs are not set, so as to not blow away the deployed file)?

**Comment by cherylking** [comment]
@five-iron I see. So I can understand why you wouldn't want it deleted from a pre-installed Liberty, but we have nothing built into the code to prevent that from getting overwritten. The problem is our plugin will not know if that file was pre-existing or came from our plugin configuration on a previous run. Perhaps we can have some special logic if the user is pointing to a pre-installed Liberty, then leave the files as is unless plugin configuration is specified currently. I will discuss with my team.

**Comment by five-iron** [comment]
@cherylking Do you know when this could get released / when the next regular deployment cycle might be?

**Comment by cherylking** [comment]
@five-iron We typically wait for more fixes to go in, but it is not a problem for me to do a minor fix release if this is important for your forward development/work. Let me see if I can fit this in my schedule tomorrow or early next week.

**Comment by five-iron** [comment]
Don't sweat it if you can't fit in, it's not a blocker for us just a minor annoyance.

**Comment by cherylking** [comment]
Ok, thanks. I went ahead and create a snapshot if you want to give it a try. Are you familiar with how to pull in snapshots from Sonatype?

**Comment by five-iron** [comment]
Hm no I am not familiar with that. I tried searching maven.org but can't find snapshots anywhere for liberty-gradle-plugin.

**Comment by cherylking** [comment]
@five-iron The [readme](Liberty Tools helps you quickly a) has a small bit on using snapshots. The version would be `3.5.2-SNAPSHOT`.

**Comment by five-iron** [comment]
Thanks I was able to download the snapshot and verify that it works as intended.
