### ISSUE TITLE
CompileJSP doc has the wrong description of jspVersion

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/ci.gradle#788]
The topic https://github.com/OpenLiberty/ci.gradle/blob/main/docs/compileJsp.md has the same description for both of the attributes.

The maven version is correct so should be copied in. https://github.com/OpenLiberty/ci.maven/blob/main/docs/compile-jsp.md#compile-jsps

**Comment by cherylking** [comment]
Fixed in this [commit](https://github.com/OpenLiberty/ci.gradle/commit/d3e63cef258019a64d6e19c50654cdc243b3e5dd). Thanks for pointing it out Alasdair.
