### ISSUE TITLE
Support for Spring Framework 3.0

### ISSUE THREAD

**Issue by Anu-Shaw** [OpenLiberty/ci.gradle#793]
https://github.com/OpenLiberty/ci.gradle/blob/7d82442b6e3226a341abc2b3d1f0b1cca6f463c0/src/main/groovy/io/openliberty/tools/gradle/LibertyTasks.groovy#L91

When we upgrade to latest spring version, the build fails with error 

Could not determine the dependencies of task ':deploy'.
> Task with path 'bootRepackage' not found in root project 'com.ibm.external.core.api'.

This is because the else block makes an assumption, that if its not version 2, it must be version 1.5.x.

**Comment by cherylking** [comment]
@Anu-Shaw Thank you for reporting this issue. As you pointed out, our plugin currently handles 2.x and 1.5.x. We should leave this issue open for adding support for 3.x. We would require Liberty to also support 3.x though. This [issue](https://github.com/OpenLiberty/open-liberty/issues/19982) is open for that support.

**Comment by Anu-Shaw** [comment]
hi @cherylking 

Am I right to assume this is fixed now? Can we migrate to spring-boot 3.0

**Comment by cherylking** [comment]
Update on this....I plan to put out a `3.8` release the last week of November. There is currently a `3.7.1-SNAPSHOT` available with this support if anyone would like to try that. See the readme for instructions on using a snapshot.

**Comment by cherylking** [comment]
This support was released in version `3.8` of the plugin.
