### ISSUE TITLE
Dev mode does not resolve the loose app config file name from dropins

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/ci.gradle#796]
Here: https://github.com/OpenLiberty/ci.gradle/blob/2bdeb932bc0c7c15a3e0c681dbaf9eb190dd781b/src/main/groovy/io/openliberty/tools/gradle/tasks/DevTask.groovy#L945-L948 
we pass `dropins` to `getLooseAppConfigFile` but then we still use `server.deploy.apps` to split the app list to resolve the loose config file name: https://github.com/OpenLiberty/ci.gradle/blob/9833ca41222937d898f193ebd8fac860f93e908b/src/main/groovy/io/openliberty/tools/gradle/tasks/AbstractServerTask.groovy#L1103.

**Comment by cherylking** [comment]
Is this done? If so, please close. @mattbsox
