### ISSUE TITLE
Add support for Gradle 8.x

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/ci.gradle#799]
The Gradle 8.0 version was published in February 2023. Need to add support for it. See this [issue](https://github.com/OpenLiberty/ci.gradle/issues/620) that might need to be addressed as part of this.

**Comment by cherylking** [comment]
https://docs.gradle.org/8.0/release-notes.html

**Comment by cherylking** [comment]
Need to address #803.

**Comment by AndiCover** [comment]
Hi @cherylking, when will this be addressed/planned?
Thanks!

**Comment by cherylking** [comment]
@AndiCover We currently have a couple other high priority items we are working on. I don't have an outlook for this at this time. I'll update here when someone is assigned to work on it.

**Comment by cherylking** [comment]
Resolved by PR #813.
