### ISSUE TITLE
Gradle plugin download endpoint is unstable

### ISSUE THREAD

**Issue by ArkUmbra** [OpenLiberty/ci.gradle#805]
Over the last few days I have noticed _intermittent_ issues where our CI builds will fail because of an error when trying to download this plugin.  If we retry the build a couple of times it will eventually succeed. 

Is this an issue the team is aware of?

For reference, here is a (probably non-exhaustive) list of approximate times where I have seen errors occurring and the corresponding stracktrace. If there any further information I can provide, please let me know.

# Plugin version
id 'io.openliberty.tools.gradle.Liberty' version '3.5.2'

# Approximate times
March 24th 4:02:07 PM GMT+09:00 ~ March 24th 4:03:35 PM GMT+09:00
March 27th 9:24:47 AM GMT+09:00 ~ March 27th 9:34:49 AM GMT+09:00

# Gradle build stack trace
```
* What went wrong:
A problem occurred configuring root project '<PROJECT NAME HERE>'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve gradle.plugin.io.openliberty.tools:ci.gradle:3.5.2.
     Required by:
         project : > io.openliberty.tools.gradle.Liberty:io.openliberty.tools.gradle.Liberty.gradle.plugin:3.5.2
      > Could not resolve gradle.plugin.io.openliberty.tools:ci.gradle:3.5.2.
         > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/io/openliberty/tools/ci.gradle/3.5.2/ci.gradle-3.5.2.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/io/openliberty/tools/ci.gradle/3.5.2/ci.gradle-3.5.2.pom'. Received status code 503 from server: Service Unavailable
```

# Error when trying to view plugin webpage
I _think_ this was when trying to open the page here  (apologies for not screencapping the actual URL) https://plugins.gradle.org/plugin/io.openliberty.tools.gradle.Liberty
 

![Screen Shot 2023-03-27 at 9 37 52](https://user-images.githubusercontent.com/660302/227816570-78af84f9-8378-459e-bc26-c4b33d220f81.png)

**Comment by cherylking** [comment]
Probably due to [this](https://status.gradle.com/?utm_source=embed) posted on their download site.

**Comment by cherylking** [comment]
![Screenshot 2023-03-27 at 8 05 14 AM](https://user-images.githubusercontent.com/29436451/227946995-8ce261a5-5871-4ab6-b5d3-586383b0c768.png)

**Comment by ArkUmbra** [comment]
Ah, thank you! In that case, I will close this issue for now.
