### ISSUE TITLE
Unable to stop server if adding runtimeUrl configuration

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/ci.gradle#810]
- Get a gradle project from https://openliberty.io/start/ or by following command
  - `curl -o inventory.zip 'https://start.openliberty.io/api/start?a=inventory&b=maven&e=9.1&g=io.openliberty.deepdive&j=11&m=5.0'`
- `unzip inventory.zip -d inventory`
- `cd inventory`
- update the build.gradle by adding the runtimeUrl configuration as following:
```
...
dependencies {
    // provided dependencies
    providedCompile 'jakarta.platform:jakarta.jakartaee-api:9.1.0' 
    providedCompile 'org.eclipse.microprofile:microprofile:5.0' 

}

liberty {
    install {
        runtimeUrl='https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2023-03-31_0433/openliberty-all-23.0.0.3-cl230420230331-0433.zip'
    }
}

clean.dependsOn 'libertyStop'
```
- `./gradlew clean war libertyCreate installFeature deploy`
- `./gradlew libertyStart`
- `pgrep java` should show 2 pids
- `./gradlew libertyStop`
- `pgrep java` should show 1 pid but 2
  - i.e. the liberty server is still running 

Expectation:
- the liberty server should be stopped

**Comment by gkwan-ibm** [comment]
This issue affects the guide-liberty-deep-dive-gradle repository automated daily test.

**Comment by cherylking** [comment]
This only happens with nightly builds which are not a supported scenario by the plugins. The plugin expects to find the features json file in MC for the OpenLiberty version installed, which will not exist for a nightly build. Here is the exception stack trace:

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.openliberty.features:features:23.0.0.3.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/io/openliberty/features/features/23.0.0.3/features-23.0.0.3.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :
2023-04-03T15:32:50.785-0500 [DEBUG] [org.gradle.api.Task] Exception received: Cannot find JSONs for to the installed runtime from the Maven repository.
io.openliberty.tools.common.plugins.util.PluginScenarioException: Cannot find JSONs for to the installed runtime from the Maven repository.
        at io.openliberty.tools.common.plugins.util.InstallFeatureUtil.<init>(InstallFeatureUtil.java:159)
        at io.openliberty.tools.gradle.tasks.AbstractFeatureTask$InstallFeatureTaskUtil.<init>(AbstractFeatureTask.groovy:95)
```
