### ISSUE TITLE
Enable Verify=all Test once Liberty 23.0.0.12 is available 

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/ci.gradle#856]
VerifyFeatureTest for feature verify=all case needs to be enabled once this [fix](https://github.com/OpenLiberty/open-liberty/pull/26602) is available in Liberty 23.0.0.12. 
We expect this has no impact on users running installFeature task, unless they have some complicated build that runs the task multiple times.

**Comment by cherylking** [comment]
Closing since PR was merged.
