### ISSUE TITLE
Liberty Gradle Plugin 3.7 seems to require use of JDK19

### ISSUE THREAD

**Issue by UlrichLohrmann** [OpenLiberty/ci.gradle#857]
Hi, 
I have developed an additional Gradle Pluging to simplify use of Open Liberty Gradle Plugin in our Environment. I use Adotium JDK 17 LTS Version for my build. In the Gradle build file I import the Open Liberty Gradle Plugin with the following statements.

`
buildscript {
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.7'
    }
}
.
dependencies {
    .
    implementation 'io.openliberty.tools:liberty-gradle-plugin:3.7'
    .
}
`

If I use Version 3.7 as shown above I get the following message as soon as Gradle is started:

Unsupported class file major version 63

This means that I have to use at least JDK19 for my build.

If I use version 3.6.2 of the Liberty Gradle Plugin, everything works fine with JDK17. So it seems to me that either the Open Liberty Plugin or one of its transitive dependencies requires JDK19. The release notes of version 3.7 don't have any comment concerning JDK19.

Could you please give a hint whether JDK19 is required for Open Liberty Gradle plugin Version 3.7?

Best regards
Ulrich

**Comment by sreich** [comment]
I'm interested in this too, before I try to upgrade

Do you not use Java toolchains as Gradle highly recommends?

This has other benefits and decouples the execution of Gradle from your actual build. Also enables you to test and run them side by side. 

But ultimately, Gradle itself would need to be executed with whatever minimum there is(like this issue), but that doesn't imply or should not affect your builds for your code themselves unless you did it incorrectly (like not using toolchains

**Comment by cherylking** [comment]
Version `3.7` definitely should not require Java 19. We ran our builds/tests on Java 8, 11 and 17. The Java compiler source/target in our build.gradle still says `1_8`...as in Java 8.

What version of Gradle are you using?

**Comment by cherylking** [comment]
@sreich Thank you for your input. There is an issue open to explore using toolchains. We have not had the bandwith to prioritize that over other issues yet. Contributions are welcome.

**Comment by cherylking** [comment]
@UlrichLohrmann I just tested a Gradle project locally and it worked fine with the following:

Liberty Gradle Plugin: 3.7
Java: 17.0.5
Gradle: 7.6

**Comment by UlrichLohrmann** [comment]
I use Gradle 7.5. The build process uses a Java Toolchain

`
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.ADOPTIUM
    }
}
`

I will try to make a small sample to reproduce.

**Comment by cherylking** [comment]
Here's the Gradle [issue](https://github.com/gradle/gradle/issues/24390) that tracked this problem.

**Comment by UlrichLohrmann** [comment]
Thank your for your inventigations. I can confirm that problem does not longer occur with Gradle 7.6 nor with Gradle 7.6.1.  Thank you for help with this issue.
