### ISSUE TITLE
Missing logging and getting ClassNotFound for some classes

### ISSUE THREAD

**Issue by paulbarr** [OpenLiberty/ci.gradle#866]
Hey,
I was using IntelliJ and I have switched to vscode
I have setup my java project and installed the liberty plugin
I am seeng a number of issues:

 - No logging
     - We use TinyLogging
     - In the build.gradle file we define a tinylogging.properties file that configures the logging
     - We build this into the war
     - However, for hot-deploy in Intellij we had to manually copy this (and other files) to a specific location..maybe we need to add something extra here?
     
  This is my build.gradle file
  
  
[build.gradle.zip](https://github.com/OpenLiberty/ci.gradle/files/13515709/build.gradle.zip)

**Comment by paulbarr** [comment]
Also I am getting the following error when I try to execute certain paths:

com.ibm.cloud.lands.rules.RuleEngineUtils (initialization failure)

However, this may be related to the logging issue above.
If the logging issue is casued by the tinylog.properties file not being detected, our rule engine needs to read other files that I suspect are not being detected in the same way

**Comment by cherylking** [comment]
> However, for hot-deploy in Intellij we had to manually copy this (and other files) to a specific location..maybe we need to add something extra here?

Where did you copy them to to get it working?

**Comment by paulbarr** [comment]
This is where we used to put them

<img width="337" alt="image" src="https://github.com/OpenLiberty/ci.gradle/assets/16646094/f9416ddc-ae8d-4d11-915d-38a9d6ac1049">

**Comment by cherylking** [comment]
Please try putting the `tinylog.properties` in `src/main/resources` to see if that helps.

**Comment by paulbarr** [comment]
So the issue was that when I was building teh war I was copying in the resource files from another location
Instead I now updated the source set definition to include those as resources and everything started working :)

So in build.gradle Inow have this defining my source set

```
sourceSets {
    main {
        java {
            srcDir 'src/'
            exclude 'main/**/*'
        }
        resources {
            srcDirs = ['WebContent/WEB-INF']
        }
    }
```
