### ISSUE TITLE
When using the liberty plugin request.getServletContext().getRealPath(File.separator) always return null

### ISSUE THREAD

**Issue by paulbarr** [OpenLiberty/ci.gradle#872]
I start my system using the libertyDev command
Everything is working fine
However, when I call code that has this: request.getServletContext().getRealPath(File.separator) it always returns null
Is there a setting that will allow this to return a real path?
In my server.xml I have set this:

```<applicationManager autoExpand="true" />```

**Comment by cherylking** [comment]
@paulbarr This seems like a question for Open Liberty itself? I presume you get the same behavior when not using our plugin. Correct me if I am wrong.

**Comment by paulbarr** [comment]
This looks to be an OpenLiberty issue related to loose config. I'll close this out
