### ISSUE TITLE
File tracking docker question for artifact files

### ISSUE THREAD

**Issue by sreich** [OpenLiberty/ci.gradle#892]
Hey, I'm following: https://github.com/OpenLiberty/ci.gradle/blob/main/docs/libertyDev.md#file-tracking

and have a question. I understand the advice against wildcards in general, so for config files and such...

But, does this advice also apply to the artifact file too? Should I prefer using explicit `COPY` commands for those, too?

**Comment by TrevCraw** [comment]
Hi @sreich , thank you for the question. You should be OK to use a wild card as part of the artifact name. Just to verify, how exactly were you intending to write the artifact line(s) in the Containerfile/Dockerfile?

**Comment by sreich** [comment]
@TrevCraw 
like so:

`COPY --chown=1001:0 \
    build/libs/*.war \
    /config/apps`

**Comment by sreich** [comment]
closing this since I'm good now and my question was answered. thanks
