### ISSUE TITLE
Facing test issues on ppc64le architecture.

### ISSUE THREAD

**Issue by vinodk99** [OpenLiberty/ci.gradle#899]
Below are the output test logs:

`
> Task :test

io.openliberty.tools.gradle.ConfigureArquillianTest > classMethod FAILED
    java.lang.AssertionError at ConfigureArquillianTest.groovy:40

io.openliberty.tools.gradle.DevContainerTest > classMethod FAILED
    java.lang.AssertionError at DevContainerTest.groovy:40

io.openliberty.tools.gradle.DevContainerTest > classMethod FAILED
    java.lang.NullPointerException at DevContainerTest.groovy:57

io.openliberty.tools.gradle.DevRecompileTest > classMethod FAILED
    java.lang.AssertionError at DevRecompileTest.groovy:41
        Caused by: java.io.IOException at DevRecompileTest.groovy:41

io.openliberty.tools.gradle.DevRecompileTest > classMethod FAILED
    java.lang.NullPointerException at DevRecompileTest.groovy:125

io.openliberty.tools.gradle.DevSkipInstallFeatureTest > classMethod FAILED
    java.lang.AssertionError at DevSkipInstallFeatureTest.groovy:41

io.openliberty.tools.gradle.DevSkipInstallFeatureTest > classMethod FAILED
    java.lang.NullPointerException at DevSkipInstallFeatureTest.groovy:76

io.openliberty.tools.gradle.DevTest > classMethod FAILED
    java.lang.AssertionError at DevTest.groovy:41
        Caused by: java.io.IOException at DevTest.groovy:41

io.openliberty.tools.gradle.DevTest > classMethod FAILED
    java.lang.NullPointerException at DevTest.groovy:295

io.openliberty.tools.gradle.GenerateFeaturesRestTest > mp21Test FAILED
    java.lang.AssertionError at GenerateFeaturesRestTest.groovy:33
        Caused by: java.io.IOException at GenerateFeaturesRestTest.groovy:33

io.openliberty.tools.gradle.GenerateFeaturesRestTest > mp30Test FAILED
    java.lang.AssertionError at GenerateFeaturesRestTest.groovy:33
        Caused by: java.io.IOException at GenerateFeaturesRestTest.groovy:33

io.openliberty.tools.gradle.GenerateFeaturesRestTest > mp41Test FAILED
    java.lang.AssertionError at GenerateFeaturesRestTest.groovy:33
        Caused by: java.io.IOException at GenerateFeaturesRestTest.groovy:33

io.openliberty.tools.gradle.GenerateFeaturesRestTest > mee7mp1Test FAILED
    java.lang.AssertionError at GenerateFeaturesRestTest.groovy:33
        Caused by: java.io.IOException at GenerateFeaturesRestTest.groovy:33

io.openliberty.tools.gradle.GenerateFeaturesRestTest > ee8mp1Test FAILED
    java.lang.AssertionError at GenerateFeaturesRestTest.groovy:33
        Caused by: java.io.IOException at GenerateFeaturesRestTest.groovy:33

io.openliberty.tools.gradle.GenerateFeaturesRestTest > jakartaTest FAILED
    java.lang.AssertionError at GenerateFeaturesRestTest.groovy:33
        Caused by: java.io.IOException at GenerateFeaturesRestTest.groovy:33

io.openliberty.tools.gradle.GenerateFeaturesTest > onlyMPUmbrellaTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > featureUnavailableConflictTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > scannerLogExistenceTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > userConflictTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > basicTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > serverXmlCommentFMTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > bothEEMPUmbrellaTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > customFeaturesTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > userAndGeneratedConflictTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > noUmbrellaTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > onlyEEUmbrellaTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > noClassFiles FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.GenerateFeaturesTest > serverXmlCommentNoFMTest FAILED
    java.lang.AssertionError at GenerateFeaturesTest.groovy:36
        Caused by: java.io.IOException at GenerateFeaturesTest.groovy:36

io.openliberty.tools.gradle.InstallDirSubProject > classMethod FAILED
    java.lang.AssertionError at InstallDirSubProject.groovy:40

io.openliberty.tools.gradle.InstallFeature_acceptLicense > classMethod FAILED
    java.lang.AssertionError at InstallFeature_acceptLicense.groovy:33

io.openliberty.tools.gradle.InstallFeature_localEsa_Test > classMethod FAILED
    java.lang.AssertionError at InstallFeature_localEsa_Test.groovy:23
        Caused by: java.io.IOException at InstallFeature_localEsa_Test.groovy:23

io.openliberty.tools.gradle.InstallFeature_multiple > classMethod FAILED
    java.lang.AssertionError at InstallFeature_multiple.groovy:33

io.openliberty.tools.gradle.InstallFeature_single > classMethod FAILED
    java.lang.AssertionError at InstallFeature_single.groovy:22

io.openliberty.tools.gradle.InstallLiberty_DefaultNoMavenRepo > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_DefaultNoMavenRepo.groovy:35

io.openliberty.tools.gradle.InstallLiberty_installDir_Invalid_Test > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_installDir_Invalid_Test.groovy:32

io.openliberty.tools.gradle.InstallLiberty_installDir_full_lifecycle_Test > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_installDir_full_lifecycle_Test.groovy:36

io.openliberty.tools.gradle.InstallLiberty_installDir_missing_wlp_Test > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_installDir_missing_wlp_Test.groovy:35

io.openliberty.tools.gradle.InstallLiberty_installDir_plus_create_server_Test > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_installDir_plus_create_server_Test.groovy:24

io.openliberty.tools.gradle.InstallLiberty_javaee7 > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_javaee7.groovy:33

io.openliberty.tools.gradle.InstallLiberty_runtimeDep_upToDate_Test > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_runtimeDep_upToDate_Test.groovy:34

io.openliberty.tools.gradle.InstallLiberty_runtimeUrl_upToDate_Test > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_runtimeUrl_upToDate_Test.groovy:33

io.openliberty.tools.gradle.InstallLiberty_webProfile7 > classMethod FAILED
    java.lang.AssertionError at InstallLiberty_webProfile7.groovy:33

io.openliberty.tools.gradle.InstallUsrFeature_toExt > test_usrFeatureExt FAILED
    java.lang.AssertionError at InstallUsrFeature_toExt.groovy:45

io.openliberty.tools.gradle.KernelInstallFeatureTest > classMethod FAILED
    java.lang.AssertionError at KernelInstallFeatureTest.groovy:34

io.openliberty.tools.gradle.LibertyApplicationConfigurationIncludeTest > classMethod FAILED
    java.lang.AssertionError at LibertyApplicationConfigurationIncludeTest.groovy:45

io.openliberty.tools.gradle.LibertyApplicationConfigurationIncludeTest > classMethod FAILED
    java.lang.AssertionError at LibertyApplicationConfigurationIncludeTest.groovy:62
        Caused by: org.gradle.testkit.runner.UnexpectedBuildFailure at LibertyApplicationConfigurationIncludeTest.groovy:60

io.openliberty.tools.gradle.LibertyApplicationConfigurationM2DefaultTest > classMethod FAILED
    java.lang.AssertionError at LibertyApplicationConfigurationM2DefaultTest.groovy:34

io.openliberty.tools.gradle.LibertyApplicationConfigurationM2Test > classMethod FAILED
    java.lang.AssertionError at LibertyApplicationConfigurationM2Test.groovy:34

io.openliberty.tools.gradle.LibertyApplicationConfigurationTest > classMethod FAILED
    java.lang.AssertionError at LibertyApplicationConfigurationTest.groovy:30

io.openliberty.tools.gradle.LibertyPackage_DefaultOutputDir_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_DefaultOutputDir_Test.groovy:33

io.openliberty.tools.gradle.LibertyPackage_DefaultOutputDir_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_DefaultOutputDir_Test.groovy:48
        Caused by: org.gradle.testkit.runner.UnexpectedBuildFailure at LibertyPackage_DefaultOutputDir_Test.groovy:46

io.openliberty.tools.gradle.LibertyPackage_archiveJarDirExist_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_archiveJarDirExist_Test.groovy:37
        Caused by: java.io.IOException at LibertyPackage_archiveJarDirExist_Test.groovy:37

io.openliberty.tools.gradle.LibertyPackage_archiveJar_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_archiveJar_Test.groovy:39

io.openliberty.tools.gradle.LibertyPackage_archiveTarGz_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_archiveTarGz_Test.groovy:33

io.openliberty.tools.gradle.LibertyPackage_archiveTar_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_archiveTar_Test.groovy:33

io.openliberty.tools.gradle.LibertyPackage_archiveZipPath_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_archiveZipPath_Test.groovy:33

io.openliberty.tools.gradle.LibertyPackage_archiveZip_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_archiveZip_Test.groovy:37

io.openliberty.tools.gradle.LibertyPackage_looseApplication_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_looseApplication_Test.groovy:33

io.openliberty.tools.gradle.LibertyPackage_noArchive_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_noArchive_Test.groovy:33

io.openliberty.tools.gradle.LibertyPackage_noAttrib_Test > classMethod FAILED
    java.lang.AssertionError at LibertyPackage_noAttrib_Test.groovy:33

io.openliberty.tools.gradle.LibertyTest > classMethod FAILED
    java.lang.AssertionError at LibertyTest.groovy:35

io.openliberty.tools.gradle.NoAppsTemplateTest > classMethod FAILED
    java.lang.AssertionError at NoAppsTemplateTest.groovy:14

io.openliberty.tools.gradle.NoServerNameTest > classMethod FAILED
    java.lang.AssertionError at NoServerNameTest.groovy:14

io.openliberty.tools.gradle.PluginRepoTest > classMethod FAILED
    java.lang.AssertionError at PluginRepoTest.groovy:30

io.openliberty.tools.gradle.PollingDevTest > classMethod FAILED
    java.lang.AssertionError at PollingDevTest.groovy:36

io.openliberty.tools.gradle.PollingDevTest > classMethod FAILED
    java.lang.NullPointerException at NullObject.java:91

io.openliberty.tools.gradle.PrepareFeatureTest > classMethod FAILED
    java.lang.AssertionError at PrepareFeatureTest.groovy:44

io.openliberty.tools.gradle.TestAppConfig > classMethod FAILED
    java.lang.AssertionError at TestAppConfig.groovy:14

io.openliberty.tools.gradle.TestAppConfig > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestAppConfig.groovy:20

io.openliberty.tools.gradle.TestAppConfigFail > classMethod FAILED
    java.lang.AssertionError at TestAppConfigFail.groovy:17

io.openliberty.tools.gradle.TestAppConfigFail > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestAppConfigFail.groovy:23

io.openliberty.tools.gradle.TestAppListsWithObjects > classMethod FAILED
    java.lang.AssertionError at TestAppListsWithObjects.groovy:14

io.openliberty.tools.gradle.TestAppListsWithObjects > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestAppListsWithObjects.groovy:20

io.openliberty.tools.gradle.TestAppendServerEnvWithConfigServerEnv > classMethod FAILED
    java.lang.AssertionError at TestAppendServerEnvWithConfigServerEnv.groovy:25

io.openliberty.tools.gradle.TestAppendServerEnvWithNoProps > classMethod FAILED
    java.lang.AssertionError at TestAppendServerEnvWithNoProps.groovy:29

io.openliberty.tools.gradle.TestAppendServerEnvWithOnlyProps > classMethod FAILED
    java.lang.AssertionError at TestAppendServerEnvWithOnlyProps.groovy:29

io.openliberty.tools.gradle.TestAppendServerEnvWithProps > classMethod FAILED
    java.lang.AssertionError at TestAppendServerEnvWithProps.groovy:29

io.openliberty.tools.gradle.TestCompileJSP > classMethod FAILED
    java.lang.AssertionError at TestCompileJSP.groovy:31

io.openliberty.tools.gradle.TestCompileJSPSource17 > classMethod FAILED
    java.lang.AssertionError at TestCompileJSPSource17.groovy:31

io.openliberty.tools.gradle.TestConfigDropinsApp > classMethod FAILED
    java.lang.AssertionError at TestConfigDropinsApp.groovy:14

io.openliberty.tools.gradle.TestConfigDropinsApp > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestConfigDropinsApp.groovy:20

io.openliberty.tools.gradle.TestCreateConfigDirUpToDate > classMethod FAILED
    java.lang.AssertionError at TestCreateConfigDirUpToDate.groovy:22

io.openliberty.tools.gradle.TestCreateWithConfigDir > classMethod FAILED
    java.lang.AssertionError at TestCreateWithConfigDir.groovy:15

io.openliberty.tools.gradle.TestCreateWithDefaultConfigDir > classMethod FAILED
    java.lang.AssertionError at TestCreateWithDefaultConfigDir.groovy:18

io.openliberty.tools.gradle.TestCreateWithFiles > classMethod FAILED
    java.lang.AssertionError at TestCreateWithFiles.groovy:15

io.openliberty.tools.gradle.TestCreateWithInlineProperties > classMethod FAILED
    java.lang.AssertionError at TestCreateWithInlineProperties.groovy:19

io.openliberty.tools.gradle.TestEclipseFacetsEar > classMethod FAILED
    java.lang.AssertionError at TestEclipseFacetsEar.groovy:31

io.openliberty.tools.gradle.TestEclipseFacetsWar > classMethod FAILED
    java.lang.AssertionError at TestEclipseFacetsWar.groovy:31

io.openliberty.tools.gradle.TestEtcOutputDir > classMethod FAILED
    java.lang.AssertionError at TestEtcOutputDir.groovy:14

io.openliberty.tools.gradle.TestEtcOutputDir > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestEtcOutputDir.groovy:20

io.openliberty.tools.gradle.TestGetAppNames > classMethod FAILED
    java.lang.AssertionError at TestGetAppNames.groovy:14

io.openliberty.tools.gradle.TestGetAppNames > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestGetAppNames.groovy:20

io.openliberty.tools.gradle.TestLooseApplication > classMethod FAILED
    java.lang.AssertionError at TestLooseApplication.groovy:30

io.openliberty.tools.gradle.TestLooseApplication > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestLooseApplication.groovy:36

io.openliberty.tools.gradle.TestLooseApplicationWithWarTask > classMethod FAILED
    java.lang.AssertionError at TestLooseApplicationWithWarTask.groovy:30

io.openliberty.tools.gradle.TestLooseApplicationWithWarTask > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestLooseApplicationWithWarTask.groovy:36

io.openliberty.tools.gradle.TestLooseEarApplication > classMethod FAILED
    java.lang.AssertionError at TestLooseEarApplication.groovy:34

io.openliberty.tools.gradle.TestLooseEarApplication > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestLooseEarApplication.groovy:40

io.openliberty.tools.gradle.TestLooseEarApplicationEarlibs > classMethod FAILED
    java.lang.AssertionError at TestLooseEarApplicationEarlibs.groovy:31

io.openliberty.tools.gradle.TestLooseEarApplicationEarlibs > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestLooseEarApplicationEarlibs.groovy:37

io.openliberty.tools.gradle.TestLooseWarWithLooseJar > classMethod FAILED
    java.lang.AssertionError at TestLooseWarWithLooseJar.groovy:30

io.openliberty.tools.gradle.TestMultiModuleLooseEar > classMethod FAILED
    java.lang.AssertionError at TestMultiModuleLooseEar.groovy:34

io.openliberty.tools.gradle.TestMultiModuleLooseEar > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestMultiModuleLooseEar.groovy:40

io.openliberty.tools.gradle.TestOutputDirs > classMethod FAILED
    java.lang.AssertionError at TestOutputDirs.groovy:14

io.openliberty.tools.gradle.TestOutputDirs > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestOutputDirs.groovy:20

io.openliberty.tools.gradle.TestPluginConfigFile > classMethod FAILED
    java.lang.AssertionError at TestPluginConfigFile.groovy:28

io.openliberty.tools.gradle.TestPluginConfigFile > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestPluginConfigFile.groovy:34

io.openliberty.tools.gradle.TestSpringBootApplication20 > test_spring_boot_war_apps_20 FAILED
    java.lang.AssertionError at TestSpringBootApplication20.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication20.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication20 > test_spring_boot_dropins_20 FAILED
    java.lang.AssertionError at TestSpringBootApplication20.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication20.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication20 > test_spring_boot_war_classifier_apps_20 FAILED
    java.lang.AssertionError at TestSpringBootApplication20.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication20.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication20 > test_spring_boot_classifier_apps_20 FAILED
    java.lang.AssertionError at TestSpringBootApplication20.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication20.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication20 > test_spring_boot_apps_20 FAILED
    java.lang.AssertionError at TestSpringBootApplication20.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication20.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication30 > test_spring_boot_war_apps_30 FAILED
    java.lang.AssertionError at TestSpringBootApplication30.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication30.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication30 > test_spring_boot_classifier_apps_30_no_feature FAILED
    java.lang.AssertionError at TestSpringBootApplication30.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication30.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication30 > test_spring_boot_dropins_30 FAILED
    java.lang.AssertionError at TestSpringBootApplication30.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication30.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication30 > test_spring_boot_war_classifier_apps_30 FAILED
    java.lang.AssertionError at TestSpringBootApplication30.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication30.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication30 > test_spring_boot_classifier_apps_30 FAILED
    java.lang.AssertionError at TestSpringBootApplication30.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication30.groovy:40

io.openliberty.tools.gradle.TestSpringBootApplication30 > test_spring_boot_apps_30 FAILED
    java.lang.AssertionError at TestSpringBootApplication30.groovy:34
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestSpringBootApplication30.groovy:40

io.openliberty.tools.gradle.TestStripVersion > classMethod FAILED
    java.lang.AssertionError at TestStripVersion.groovy:14

io.openliberty.tools.gradle.TestStripVersion > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestStripVersion.groovy:20

io.openliberty.tools.gradle.TestWarTasksWithDifferentDependencies > classMethod FAILED
    java.lang.AssertionError at TestWarTasksWithDifferentDependencies.groovy:14

io.openliberty.tools.gradle.TestWarTasksWithDifferentDependencies > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at TestWarTasksWithDifferentDependencies.groovy:20

io.openliberty.tools.gradle.VerifyFeatureTest > classMethod FAILED
    java.lang.AssertionError at VerifyFeatureTest.groovy:32

io.openliberty.tools.gradle.VerifyLooseAppTestTimeoutSuccess > classMethod FAILED
    java.lang.AssertionError at VerifyLooseAppTestTimeoutSuccess.groovy:30

io.openliberty.tools.gradle.VerifyLooseAppTestTimeoutSuccess > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at VerifyLooseAppTestTimeoutSuccess.groovy:36

io.openliberty.tools.gradle.VerifyTimeoutSuccessAppsTest > classMethod FAILED
    java.lang.AssertionError at VerifyTimeoutSuccessAppsTest.groovy:14

io.openliberty.tools.gradle.VerifyTimeoutSuccessAppsTest > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at VerifyTimeoutSuccessAppsTest.groovy:20

io.openliberty.tools.gradle.VerifyTimeoutSuccessDropinsTest > classMethod FAILED
    java.lang.AssertionError at VerifyTimeoutSuccessDropinsTest.groovy:14

io.openliberty.tools.gradle.VerifyTimeoutSuccessDropinsTest > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at VerifyTimeoutSuccessDropinsTest.groovy:20

io.openliberty.tools.gradle.VerifyTimeoutSuccessListsOfAppsTest > classMethod FAILED
    java.lang.AssertionError at VerifyTimeoutSuccessListsOfAppsTest.groovy:14

io.openliberty.tools.gradle.VerifyTimeoutSuccessListsOfAppsTest > classMethod FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at VerifyTimeoutSuccessListsOfAppsTest.groovy:20

io.openliberty.tools.gradle.WLPKernelInstallFeatureTest > classMethod FAILED
    java.lang.AssertionError at WLPKernelInstallFeatureTest.groovy:28

132 tests completed, 132 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///ci.gradle/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 12s
5 actionable tasks: 1 executed, 4 up-to-date
`

OS:
[root@ed4280fc812c ci.gradle]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

**Comment by cherylking** [comment]
@vinodk99 Can you share the full gradle command that you ran please? Also what version of Java and Gradle are you using? Finally, why are you trying to run our integration tests? Are you preparing to contribute some code to our plugin?

**Comment by vinodk99** [comment]
@cherylking ,below is the details of gradle and java version and command which i try to run the tests:

`[root@ed4280fc812c ci.gradle]# ./gradlew --version

------------------------------------------------------------
Gradle 8.5
------------------------------------------------------------

Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.24 (Eclipse Adoptium 11.0.24+8)
OS:           Linux 5.14.0-70.13.1.el9_0.ppc64le ppc64le

[root@ed4280fc812c ci.gradle]# java --version
openjdk 11.0.24 2024-07-16
OpenJDK Runtime Environment Temurin-11.0.24+8 (build 11.0.24+8)
OpenJDK 64-Bit Server VM Temurin-11.0.24+8 (build 11.0.24+8, mixed mode)
'
'
[root@ed4280fc812c ci.gradle]# ./gradlew clean install check -P"test.exclude"="**/TestSpringBootApplication30*,**/TestCompileJSPSource17*,**/DevContainerTest*" -Druntime=ol -DruntimeVersion="24.0.0.6"
`

**Comment by cherylking** [comment]
@vinodk99 Thank you for the version info. Can you answer my other questions?

> Finally, why are you trying to run our integration tests? Are you preparing to contribute some code to our plugin?

Our builds/tests are run with Java 8, 11, 17 and 21 with Gradle version 8.5 and all are passing. I have no insight into why our tests would fail on ppc64le architecture and no way to test that locally. Do you have other hardware where you are able to run the tests successfully?

**Comment by vinodk99** [comment]
Hi @cherylking  i tried to check on other os also facing test failures below are the logs:

`[root@6039304b0729 ci.gradle]# ./gradlew clean install check -P"test.exclude"="/TestSpringBootApplication30*,/TestCompileJSPSource17*,**/DevContainerTest*" -Druntime=ol -DruntimeVersion="24.0.0.6"
Downloading https://services.gradle.org/distributions/gradle-8.5-bin.zip
............10%.............20%............30%.............40%.............50%............60%.............70%.............80%............90%.............100%

Welcome to Gradle 8.5!

Here are the highlights of this release:
 - Support for running on Java 21
 - Faster first use with Kotlin DSL
 - Improved error and warning messages

For more details see https://docs.gradle.org/8.5/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :test

io.openliberty.tools.gradle.VerifyFeatureTest > test_verifyALL FAILED
    java.lang.AssertionError at VerifyFeatureTest.groovy:72
        Caused by: org.gradle.testkit.runner.UnexpectedBuildFailure at VerifyFeatureTest.groovy:67

197 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///ci.gradle/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 47m 39s
15 actionable tasks: 14 executed, 1 up-to-date
[root@6039304b0729 ci.gradle]# uname -m
x86_64
`

**Comment by cherylking** [comment]
> Finally, why are you trying to run our integration tests? Are you preparing to contribute some code to our plugin?

@vinodk99 Would you mind answering this? 

Also, have you tried using the plugin on the system where the tests are failing? I would be more interested in how our tasks are failing when invoked as intended by the end user.

**Comment by vinodk99** [comment]
> > Finally, why are you trying to run our integration tests? Are you preparing to contribute some code to our plugin?
> 
> @vinodk99 Would you mind answering this?
> 
> Also, have you tried using the plugin on the system where the tests are failing? I would be more interested in how our tasks are failing when invoked as intended by the end user.

i tried to execute same steps which are mentioned on ci on both x86_64 and ppc64le platform but facing some issues on ppc64le

**Comment by cherylking** [comment]
> i tried to execute same steps which are mentioned on ci on both x86_64 and ppc64le platform but facing some issues on ppc64le

I don't know what that means. If you have a real end user scenario (using the tasks our plugin provides) that you would like me to debug, please provide a sample app and recreation steps. There is nothing I can do to look into our integration tests failing on the ppc64le platform in your environment.

**Comment by vinodk99** [comment]
> ./gradlew clean install check -P"test.exclude"="/TestSpringBootApplication30*,/TestCompileJSPSource17*,**/DevContainerTest*" -Druntime=ol -DruntimeVersion="24.0.0.6"

Hi @cherylking these are the steps which i'm using to build and test:

yum install git wget gcc gcc-c++ java-21-openjdk java-21-openjdk-devel java-21-openjdk-headless -y
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
export PATH=$PATH:$JAVA_HOME

wget https://archive.apache.org/dist/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
tar -zxf apache-maven-3.8.7-bin.tar.gz
cp -R apache-maven-3.8.7 /usr/local
ln -s /usr/local/apache-maven-3.8.7/bin/mvn /usr/bin/mvn

git clone https://github.com/OpenLiberty/ci.gradle/
cd ci.gradle
git checkout liberty-gradle-plugin-3.8.3

git clone https://github.com/OpenLiberty/ci.common
git clone https://github.com/OpenLiberty/ci.ant

mvn -V clean install -f ci.ant --batch-mode --no-transfer-progress --errors -DtrimStackTrace=false -DskipTests
mvn -V clean install -f ci.common --batch-mode --no-transfer-progress --errors -DtrimStackTrace=false -DskipTests


./gradlew clean install check -P"test.exclude"="/TestSpringBootApplication30*,/TestCompileJSPSource17*,**/DevContainerTest*" -Druntime=ol -DruntimeVersion="24.0.0.6"

**Comment by cherylking** [comment]
> Why are you trying to run our integration tests? Are you preparing to contribute some code to our plugin?

**Comment by vinodk99** [comment]
> > Why are you trying to run our integration tests? Are you preparing to contribute some code to our plugin?

The integratio tests are running by default and also i'm not contributing to code

**Comment by cherylking** [comment]
> The integration tests are running by default and also i'm not contributing to code

That is because you are telling gradle to run them. If you are not contributing code, why are you cloning and building our repos and plugin? You can use our plugin without cloning and building them locally. They are published to Maven Central and the Gradle repository.

**Comment by vinodk99** [comment]
> > The integration tests are running by default and also i'm not contributing to code
> 
> That is because you are telling gradle to run them. If you are not contributing code, why are you cloning and building our repos and plugin? You can use our plugin without cloning and building them locally. They are published to Maven Central and the Gradle repository.

Thanks for this infomration

**Comment by cherylking** [comment]
Here is a [guide](https://openliberty.io/guides/gradle-intro.html#running-the-application) that shows using our plugin with Liberty. It may be that you will get errors when running our tasks on this platform. If so, open an issue specific to that with a sample project and recreation steps.
